### ISSUE TITLE
Did not continue to work as stated

### ISSUE THREAD

**Issue by duckfromdiscord** [FoxxMD/multi-scrobbler#103]
**Describe the bug**
It got stuck in a loop of "polling request failed," and eventually stated that it had lost Spotify API permissions. It also said that it would continue to work, but at the end of the stacktrace, it exited. After a restart and no change to Spotify API perms, it continued to work normally.

**To Reproduce**
1. Run multi-scrobbler for some time properly
2. Eventual crash

**Logs**
A couple of retries:
```
[Sources] [Spotify - unnamed] Poll retries (4) less than max poll retries (5), restarting polling after 64 second delay...
[Sources] [Spotify - unnamed] Polling started
[Sources] [Spotify - unnamed] Refreshing recently played
[Sources] [Spotify - unnamed] Request failed but retries (0) less than max (1), retrying request after 2 seconds...
[Sources] [Spotify - unnamed] Request failed on retry (1) with no more retries permitted (max 1)
[Sources] [Spotify - unnamed] Request failed on retry (1) with no more retries permitted (max 1)
ErrorWithCause:
    at h.callApi (CWD/build/server.js:12:47048)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async h.getCurrentPlaybackState (CWD/build/server.js:12:45974)
    at async h.getRecentlyPlayed (CWD/build/server.js:12:45157)
    at async h.doPolling (CWD/build/server.js:9:9734)
    at async h.startPolling (CWD/build/server.js:9:7745)
    at async h.poll (CWD/build/server.js:9:7410)
caused by: Error: connect ECONNREFUSED xx.xxx.xxx.xx:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
```
And then eventually:
```
[Sources] [Spotify - unnamed] multi-scrobbler does not have sufficient permissions to access Spotify API "Get Playback State". MS will continue to work but accuracy for determining if/when a track played from a Spotify Connect device (smart device controlled through Spotify app) may be degraded. To fix this re-authenticate MS with Spotify and restart polling.
[Sources] [Spotify - unnamed] Checking recently played API for tracks to backlog...
[Sources] [Spotify - unnamed] Request failed but retries (0) less than max (1), retrying request after 2 seconds...
[Sources] [Spotify - unnamed] Request failed on retry (1) with no more retries permitted (max 1)
[Sources] [Spotify - unnamed] Request failed on retry (1) with no more retries permitted (max 1)
ErrorWithCause:
    at h.callApi (CWD/build/server.js:12:47048)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async h.getPlayHistory (CWD/build/server.js:12:45578)
    at async h.onPollPostAuthCheck (CWD/build/server.js:12:48657)
    at async h.poll (CWD/build/server.js:9:7376)

caused by: Error: connect ECONNREFUSED xx.xxx.xxx.xx:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
```
After which it crashed directly back to command line.

**Versions (please complete the following information):**

- multi-scrobbler: stable 0.5.2 on flatpak
- maloja https://github.com/krateng/maloja/commit/58b44f6d1ec02bd8f8e0b014553c1626729dc233

**Additional context**
None

**Comment by FoxxMD** [comment]
You can test these changes using the flathub beta repo

```bash
flatpak remote-add flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
flatpak install flathub-beta io.github.foxxmd.multiscrobbler
```
