### ISSUE TITLE
LastFM Error - Login: User required to be logged in

### ISSUE THREAD

**Issue by FozzieHi** [FoxxMD/multi-scrobbler#105]
**Describe the bug**
I get an error when trying to scrobble to LastFM. I have authenticated via the callbackUri successfully (i.e. I get an OK after following the URL), but the LastFM client has a status of "Idle" and cannot send any scrobbles.

The following is my client config (some things redacted with `x`):
```json
{
  "name": "LastFM",
  "type": "lastfm",
  "data": {
    "apiKey": "x",
    "secret": "x",
    "redirectUri": "x/lastfm/callback"
  }
}
```

Note: The example LastFM config seemed to be missing a `type` property, so I added it above.

**Logs**
```
error   : [Scrobblers] [Lastfm - LastFM] Login: User required to be logged in
Error: 
    at CWD/node_modules/lastfm-node-client/lib/ApiRequest.js:136:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async d.callApi (CWD/build/server.js:1:15592)
    at async u.refreshScrobbles (CWD/build/server.js:1:48956)
    at async u.doProcessing (CWD/build/server.js:1:42594)
    at async u.startScrobbling (CWD/build/server.js:1:39715)
    at async u.initScrobbleMonitoring (CWD/build/server.js:1:39243)
```

**Versions (please complete the following information):**
Provide version information for any related sources/clients.

- multi-scrobbler: latest tag on Docker Hub, is there a way to get the version within the app?

**Comment by FozzieHi** [comment]
I did some searching and it seems like this is similar to an issue fixed in nrubin29/finale#25. Disabling `Hide recent listening information` in my LastFM settings fixes the issue for me. The solution in the linked PR is to send the `session` key when calling a particular endpoint, do we need to do the same here to fix it?

**Comment by FoxxMD** [comment]
Thanks for the hint on the fix for this. You can test the fix in the docker image `foxxmd/multi-scrobbler:develop`

**Comment by FozzieHi** [comment]
> Thanks for the hint on the fix for this. You can test the fix in the docker image `foxxmd/multi-scrobbler:develop`

Thanks, that has fixed it. Also thanks for adding the version info to the UI :)

**Comment by FoxxMD** [comment]
This should now be fixed in [0.6.2](https://github.com/FoxxMD/multi-scrobbler/releases/tag/0.6.2)
