### ISSUE TITLE
LastFM permission errors in log

### ISSUE THREAD

**Issue by koehntopp** [FoxxMD/multi-scrobbler#115]
[Please check the FAQ](https://github.com/FoxxMD/multi-scrobbler/blob/master/docsite/docs/FAQ.md) before submitting a bug report.

**Describe the bug**
Hi,

I'm getting frequent permission errors (see below). Operation continues and recovers, but it would be nice to to get the error in the first place?

2023-12-10T23:09:20+01:00 info    : [Scrobblers] [Listenbrainz - brainz] Scrobbled (Backlog) => (Lastfm) Trevor Horn - Swimming Pools (Drank) @ 2023-12-10T23:05:16+01:00
2023-12-10T23:09:15+01:00 info    : [Sources] [Lastfm - myLastFm] Discovered => Trevor Horn - Swimming Pools (Drank) @ 2023-12-10T23:05:16+01:00
2023-12-10T14:47:11+01:00 warn    : [API - Lastfm - myLastFm] API call was not good but recoverable (operation failed), retrying in 1.5 seconds...
2023-12-10T07:44:11+01:00 info    : [Sources] [Lastfm - myLastFm] Polling started
2023-12-10T07:43:56+01:00 info    : [Sources] [Lastfm - myLastFm] Poll retries (2) less than max poll retries (5), restarting polling after 15 second delay...
2023-12-10T07:43:56+01:00 error   : [Sources] [Lastfm - myLastFm] Authentication Failed - You do not have permissions to access the service

**To Reproduce**
Normal runtime behaviour

**Expected behavior**

**Logs**
If possible reproduce the issue with [debug logging ON](https://github.com/FoxxMD/multi-scrobbler/blob/master/docsite/docs/FAQ.md#turn-on-debug-logging)

```
2023-12-10T07:43:56+01:00 error   : [Sources] [Lastfm - myLastFm] Authentication Failed - You do not have permissions to access the service
Error: 
    at CWD/node_modules/lastfm-node-client/lib/ApiRequest.js:136:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async u.callApi (CWD/build/server.js:1:16787)
    at async l.getRecentlyPlayed (CWD/build/server.js:12:5058)
    at async l.doPolling (CWD/build/server.js:9:14672)
    at async l.startPolling (CWD/build/server.js:9:12562)
    at async l.poll (CWD/build/server.js:9:12202)
2023-12-10T07:43:56+01:00 error   : [Sources] [Lastfm - myLastFm] Error occurred while polling
2023-12-10T07:43:47+01:00 error   : [Sources] [Lastfm - myLastFm] Authentication Failed - You do not have permissions to access the service
Error: 
    at CWD/node_modules/lastfm-node-client/lib/ApiRequest.js:136:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async u.callApi (CWD/build/server.js:1:16787)
    at async l.getRecentlyPlayed (CWD/build/server.js:12:5058)
    at async l.doPolling (CWD/build/server.js:9:14672)
    at async l.startPolling (CWD/build/server.js:9:12562)
    at async l.poll (CWD/build/server.js:9:12202)
2023-12-10T07:43:47+01:00 error   : [Sources] [Lastfm - myLastFm] Error occurred while polling```

**Versions (please complete the following information):**
Provide version information for any related sources/clients.

- multi-scrobbler: [e.g. 0.6.2 on docker]

**Comment by FoxxMD** [comment]
Is this still occurring? The error message you are seeing

> Authentication Failed - You do not have permissions to access the service

Is directly from last.fm but is also probably the default message when they return a 403/401 status which _could_ happen if they are having API issues upstream. They do tend to have API reliability issues more often than you'd expect. If MS recovers after some time then it's likely just that, a temporary upstream issue, rather than an actual issue with MS.

**Comment by koehntopp** [comment]
Yes, it's still occuring, and I also understand it's not a problem.
I'm just suggesting the error message should be caught, and ignored if a retry is successful.
Makes the log prettier ;)

**Comment by FoxxMD** [comment]
I'm not going to suppress 401/403 responses because it's important those fail fast for actual authentication issues. It's Last.fm's responsibility to return the correct HTTP response if they are having general availability issues from their side (and its not 401/403, its 5xx). In fact their [rest spec](https://www.last.fm/api/rest) specifies a [list of known errors](https://www.last.fm/api/errorcodes) that [multi-scrobbler already uses for retry logic](https://github.com/FoxxMD/multi-scrobbler/blob/633e366e82db1ec8608221b1862c00149769dec2/src/backend/common/vendor/LastfmApiClient.ts#L27), they just need to actually send them!

I've [added additional checks](https://github.com/FoxxMD/multi-scrobbler/blob/633e366e82db1ec8608221b1862c00149769dec2/src/backend/common/vendor/LastfmApiClient.ts#L114) to retry (and suppress errors) if the api call results in a general network issue (unreachable, dns, timeout, etc...). This won't stop logging 401/403 errors but it should cover all other cases.
