### ISSUE TITLE
Authentication error trying to setup Nextcloud Music app as subsonic source

### ISSUE THREAD

**Issue by afermar** [FoxxMD/multi-scrobbler#136]
**Describe the bug**
Nextcloud Music app can be used as Subsonic server.
I tried to add it as subsonic source but it throws an authentication error.

**To Reproduce**
1. Generate API password in Nextcloud Music
2. Add subsonic ENV variables to multi-scrobbler docker
3. Run docker container

**Logs**
```
ErrorWithCause: 
    at SubsonicSource.initialize (CWD/src/backend/sources/AbstractSource.ts:114:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ScrobbleSources.addSource (CWD/src/backend/sources/ScrobbleSources.ts:544:18)
    at ScrobbleSources.buildSourcesFromConfig (CWD/src/backend/sources/ScrobbleSources.ts:451:25)
    at <anonymous> (CWD/src/backend/index.ts:116:9)

caused by: ErrorWithCause: Authentication test failed!
    at SubsonicSource.testAuth (CWD/src/backend/sources/AbstractSource.ts:211:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at SubsonicSource.initialize (CWD/src/backend/sources/AbstractSource.ts:110:13)
    at ScrobbleSources.addSource (CWD/src/backend/sources/ScrobbleSources.ts:544:18)
    at ScrobbleSources.buildSourcesFromConfig (CWD/src/backend/sources/ScrobbleSources.ts:451:25)
    at <anonymous> (CWD/src/backend/index.ts:116:9)

caused by: ErrorWithCause: Subsonic API returned an error => (nextcloud music | v1.16.1 | server v1.10.0) Subsonic Api Response => (41) failed: Token-based authentication not supported
    at SubsonicSource.callApi (CWD/src/backend/sources/SubsonicSource.ts:124:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at SubsonicSource.doAuthentication (CWD/src/backend/sources/SubsonicSource.ts:195:13)
    at SubsonicSource.testAuth (CWD/src/backend/sources/AbstractSource.ts:204:27)
    at SubsonicSource.initialize (CWD/src/backend/sources/AbstractSource.ts:110:13)
    at ScrobbleSources.addSource (CWD/src/backend/sources/ScrobbleSources.ts:544:18)
    at ScrobbleSources.buildSourcesFromConfig (CWD/src/backend/sources/ScrobbleSources.ts:451:25)
    at <anonymous> (CWD/src/backend/index.ts:116:9)
```

**Versions (please complete the following information):**
Provide version information for any related sources/clients.

- multi-scrobbler: [0.6.5 on docker]
- Nextcloud: [28.0.2]
- Nextlcloud Music: [1.10.0]

**Comment by FoxxMD** [comment]
This error should be fixed in `foxxmd/multi-scrobbler:develop` docker image now. 

Unfortunately the Nextcloud Music app will still be unusable as they have [not implemented the `nowPlaying` subsonic api endpoint](https://github.com/owncloud/music/pull/1079) that MS uses to track music that is playing.

**Comment by FoxxMD** [comment]
Closed in [0.7.0](https://github.com/FoxxMD/multi-scrobbler/releases/tag/0.7.0)
