### ISSUE TITLE
Authentication test failed due to a network issue - requires Docker container restart to resolve, losing queued scrobbles

### ISSUE THREAD

**Issue by infinitejones** [FoxxMD/multi-scrobbler#160]
**Describe the bug**

**Original Issues: https://github.com/FoxxMD/multi-scrobbler/issues/159**

At times, Multi-scrobbler loses the ability to connect to clients, and clicking the Start button on their tiles does not re-start them. Restarting the connection seems to require a restart of the Docker container, which has a side effect of losing queued scrobbles.

**Screenshot**
![image](https://github.com/FoxxMD/multi-scrobbler/assets/5801868/46a60335-dd3a-4b61-8301-4fc54ea0d105)

Clicking Start does not re-start the connection. Clicking re-authenticate for Last.fm _does_ start the re-authentication workflow.

**Expected behavior**
I'd like to be able to re-connect to the clients without needing to restart the Docker container.

**Logs**
If possible reproduce the issue with [debug logging ON](https://github.com/FoxxMD/multi-scrobbler/blob/master/docsite/docs/FAQ.md#turn-on-debug-logging)

```
[2024-06-25 17:29:25.338 +1000] DEBUG  : [App] [Sources] [Subsonic - Navidrome] Last activity was at 2024-06-25T17:29:25+10:00 | Next check interval: 10.00s
[2024-06-25 17:29:25.336 +1000] DEBUG  : [App] [Sources] [Subsonic - Navidrome] No new tracks discovered
[2024-06-25 17:29:25.317 +1000] DEBUG  : [App] [Sources] [Subsonic - Navidrome] Refreshing recently played
[2024-06-25 17:29:16.051 +1000] WARN   : [App] [Scrobblers] [Listenbrainz - Listenbrainz] Cannot start scrobble processing because auth test failed
[2024-06-25 17:29:16.041 +1000] ERROR  : [App] [Scrobblers] [Listenbrainz - Listenbrainz] Authentication test failed! Due to a network issue. Will retry authentication on next heartbeat.
Error: Authentication test failed! Due to a network issue. Will retry authentication on next heartbeat.
    at ListenbrainzScrobbler.testAuth (CWD/src/backend/scrobblers/AbstractScrobbleClient.ts:188:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ListenbrainzScrobbler.initScrobbleMonitoring (CWD/src/backend/scrobblers/AbstractScrobbleClient.ts:458:17)
    at <anonymous> (CWD/src/backend/server/api.ts:420:9)
    at async wrappedMiddleware (CWD/node_modules/@awaitjs/express/index.js:116:7)
caused by: Error: getaddrinfo EAI_AGAIN api.listenbrainz.org
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at __node_internal_ (node:internal/errors:715:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
[2024-06-25 17:29:16.039 +1000] ERROR  : [App] [Scrobblers] [Listenbrainz - Listenbrainz] Could not communicate with Listenbrainz API
[2024-06-25 17:29:15.299 +1000] DEBUG  : [App] [Sources] [Subsonic - Navidrome] Last activity was at 2024-06-25T17:29:15+10:00 | Next check interval: 10.00s
[2024-06-25 17:29:15.297 +1000] DEBUG  : [App] [Sources] [Subsonic - Navidrome] No new tracks discovered
[2024-06-25 17:29:15.278 +1000] DEBUG  : [App] [Sources] [Subsonic - Navidrome] Refreshing recently played
[2024-06-25 17:29:11.030 +1000] INFO   : [App] [Scrobblers] [Listenbrainz - Listenbrainz] Trying to start scrobbler...
[2024-06-25 17:29:11.028 +1000] WARN   : [App] [Scrobblers] [Listenbrainz - Listenbrainz] Polling is already stopped!
[2024-06-25 17:29:11.026 +1000] INFO   : [App] [Scrobblers] [Listenbrainz - Listenbrainz] Checking (and trying) to stop scrobbler if already running...
[2024-06-25 17:29:11.024 +1000] VERBOSE: [App] [Scrobblers] [Listenbrainz - Listenbrainz] User requested (re)start via API call
[2024-06-25 17:29:05.260 +1000] DEBUG  : [App] [Sources] [Subsonic - Navidrome] Last activity was at 2024-06-25T17:29:05+10:00 | Next check interval: 10.00s
[2024-06-25 17:29:05.258 +1000] DEBUG  : [App] [Sources] [Subsonic - Navidrome] No new tracks discovered
[2024-06-25 17:29:05.238 +1000] DEBUG  : [App] [Sources] [Subsonic - Navidrome] Refreshing recently played
[2024-06-25 17:28:55.223 +1000] DEBUG  : [App] [Sources] [Subsonic - Navidrome] Last activity was at 2024-06-25T17:28:55+10:00 | Next check interval: 10.00s
[2024-06-25 17:28:55.221 +1000] DEBUG  : [App] [Sources] [Subsonic - Navidrome] No new tracks discovered
[2024-06-25 17:28:55.202 +1000] DEBUG  : [App] [Sources] [Subsonic - Navidrome] Refreshing recently played
[2024-06-25 17:28:45.185 +1000] DEBUG  : [App] [Sources] [Subsonic - Navidrome] Last activity was at 2024-06-25T17:28:45+10:00 | Next check interval: 10.00s
[2024-06-25 17:28:45.183 +1000] DEBUG  : [App] [Sources] [Subsonic - Navidrome] No new tracks discovered
[2024-06-25 17:28:45.163 +1000] DEBUG  : [App] [Sources] [Subsonic - Navidrome] Refreshing recently played
[2024-06-25 17:28:35.146 +1000] DEBUG  : [App] [Sources] [Subsonic - Navidrome] Last activity was at 2024-06-25T17:28:35+10:00 | Next check interval: 10.00s
[2024-06-25 17:28:35.144 +1000] DEBUG  : [App] [Sources] [Subsonic - Navidrome] No new tracks discovered
[2024-06-25 17:28:35.124 +1000] DEBUG  : [App] [Sources] [Subsonic - Navidrome] Refreshing recently played
[2024-06-25 17:28:27.509 +1000] WARN   : [App] [Scrobblers] [Lastfm - last.fm] Cannot start scrobble processing because auth test failed
[2024-06-25 17:28:27.493 +1000] ERROR  : [App] [Scrobblers] [Lastfm - last.fm] Authentication test failed! Due to a network issue. Will retry authentication on next heartbeat.
Error: Authentication test failed! Due to a network issue. Will retry authentication on next heartbeat.
    at LastfmScrobbler.testAuth (CWD/src/backend/scrobblers/AbstractScrobbleClient.ts:188:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at LastfmScrobbler.initScrobbleMonitoring (CWD/src/backend/scrobblers/AbstractScrobbleClient.ts:458:17)
    at <anonymous> (CWD/src/backend/server/api.ts:420:9)
    at async wrappedMiddleware (CWD/node_modules/@awaitjs/express/index.js:116:7)
caused by: Error: API call failed due -> API call timed out <- after max retries hit 2
    at LastfmApiClient.callApi (CWD/src/backend/common/vendor/LastfmApiClient.ts:133:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at LastfmApiClient.testAuth (CWD/src/backend/common/vendor/LastfmApiClient.ts:181:30)
    at LastfmScrobbler.doAuthentication (CWD/src/backend/scrobblers/LastfmScrobbler.ts:48:20)
    at LastfmScrobbler.testAuth (CWD/src/backend/scrobblers/AbstractScrobbleClient.ts:182:27)
    at LastfmScrobbler.initScrobbleMonitoring (CWD/src/backend/scrobblers/AbstractScrobbleClient.ts:458:17)
    at <anonymous> (CWD/src/backend/server/api.ts:420:9)
    at async wrappedMiddleware (CWD/node_modules/@awaitjs/express/index.js:116:7)
caused by: Error: getaddrinfo EAI_AGAIN ws.audioscrobbler.com
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at __node_internal_ (node:internal/errors:715:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
[2024-06-25 17:28:27.490 +1000] ERROR  : [App] [Scrobblers] [API - Lastfm - last.fm] Testing auth failed
[2024-06-25 17:28:25.105 +1000] DEBUG  : [App] [Sources] [Subsonic - Navidrome] Last activity was at 2024-06-25T17:28:25+10:00 | Next check interval: 10.00s
[2024-06-25 17:28:25.103 +1000] DEBUG  : [App] [Sources] [Subsonic - Navidrome] No new tracks discovered
[2024-06-25 17:28:25.083 +1000] DEBUG  : [App] [Sources] [Subsonic - Navidrome] Refreshing recently played
[2024-06-25 17:28:19.479 +1000] WARN   : [App] [Scrobblers] [API - Lastfm - last.fm] API call failed due to network issue (getaddrinfo EAI_AGAIN ws.audioscrobbler.com), retrying in 3 seconds...
[2024-06-25 17:28:15.065 +1000] DEBUG  : [App] [Sources] [Subsonic - Navidrome] Last activity was at 2024-06-25T17:28:15+10:00 | Next check interval: 10.00s
[2024-06-25 17:28:15.063 +1000] DEBUG  : [App] [Sources] [Subsonic - Navidrome] No new tracks discovered
[2024-06-25 17:28:15.041 +1000] WARN   : [App] [Scrobblers] [Listenbrainz - Listenbrainz] Cannot start scrobble processing because auth test failed
[2024-06-25 17:28:15.032 +1000] ERROR  : [App] [Scrobblers] [Listenbrainz - Listenbrainz] Authentication test failed! Due to a network issue. Will retry authentication on next heartbeat.
Error: Authentication test failed! Due to a network issue. Will retry authentication on next heartbeat.
    at ListenbrainzScrobbler.testAuth (CWD/src/backend/scrobblers/AbstractScrobbleClient.ts:188:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ListenbrainzScrobbler.initScrobbleMonitoring (CWD/src/backend/scrobblers/AbstractScrobbleClient.ts:458:17)
    at <anonymous> (CWD/src/backend/server/api.ts:420:9)
    at async wrappedMiddleware (CWD/node_modules/@awaitjs/express/index.js:116:7)
caused by: Error: getaddrinfo EAI_AGAIN api.listenbrainz.org
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at __node_internal_ (node:internal/errors:715:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
[2024-06-25 17:28:15.029 +1000] ERROR  : [App] [Scrobblers] [Listenbrainz - Listenbrainz] Could not communicate with Listenbrainz API
[2024-06-25 17:28:14.898 +1000] DEBUG  : [App] [Sources] [Subsonic - Navidrome] Refreshing recently played
[2024-06-25 17:28:12.969 +1000] WARN   : [App] [Scrobblers] [API - Lastfm - last.fm] API call failed due to network issue (getaddrinfo EAI_AGAIN ws.audioscrobbler.com), retrying in 1.5 seconds...
[2024-06-25 17:28:10.021 +1000] INFO   : [App] [Scrobblers] [Listenbrainz - Listenbrainz] Trying to start scrobbler...
[2024-06-25 17:28:10.019 +1000] WARN   : [App] [Scrobblers] [Listenbrainz - Listenbrainz] Polling is already stopped!
[2024-06-25 17:28:10.017 +1000] INFO   : [App] [Scrobblers] [Listenbrainz - Listenbrainz] Checking (and trying) to stop scrobbler if already running...
[2024-06-25 17:28:10.015 +1000] VERBOSE: [App] [Scrobblers] [Listenbrainz - Listenbrainz] User requested (re)start via API call
[2024-06-25 17:28:07.961 +1000] INFO   : [App] [Scrobblers] [Lastfm - last.fm] Trying to start scrobbler...
[2024-06-25 17:28:07.958 +1000] WARN   : [App] [Scrobblers] [Lastfm - last.fm] Polling is already stopped!
[2024-06-25 17:28:07.957 +1000] INFO   : [App] [Scrobblers] [Lastfm - last.fm] Checking (and trying) to stop scrobbler if already running...
[2024-06-25 17:28:07.955 +1000] VERBOSE: [App] [Scrobblers] [Lastfm - last.fm] User requested (re)start via API call
[2024-06-25 17:28:04.882 +1000] DEBUG  : [App] [Sources] [Subsonic - Navidrome] Last activity was at 2024-06-25T17:28:04+10:00 | Next check interval: 10.00s
[2024-06-25 17:28:04.880 +1000] DEBUG  : [App] [Sources] [Subsonic - Navidrome] No new tracks discovered
[2024-06-25 17:28:04.856 +1000] DEBUG  : [App] [Sources] [Subsonic - Navidrome] Refreshing recently played
[2024-06-25 17:27:54.840 +1000] DEBUG  : [App] [Sources] [Subsonic - Navidrome] Last activity was at 2024-06-25T17:27:54+10:00 | Next check interval: 10.00s
[2024-06-25 17:27:54.838 +1000] DEBUG  : [App] [Sources] [Subsonic - Navidrome] No new tracks discovered
[2024-06-25 17:27:54.822 +1000] DEBUG  : [App] [Sources] [Subsonic - Navidrome] Refreshing recently played
[2024-06-25 17:27:44.804 +1000] DEBUG  : [App] [Sources] [Subsonic - Navidrome] Last activity was at 2024-06-25T17:27:44+10:00 | Next check interval: 10.00s
[2024-06-25 17:27:44.802 +1000] DEBUG  : [App] [Sources] [Subsonic - Navidrome] No new tracks discovered
[2024-06-25 17:27:44.786 +1000] DEBUG  : [App] [Sources] [Subsonic - Navidrome] Refreshing recently played
[2024-06-25 17:27:34.771 +1000] DEBUG  : [App] [Sources] [Subsonic - Navidrome] Last activity was at 2024-06-25T17:27:34+10:00 | Next check interval: 10.00s
[2024-06-25 17:27:34.769 +1000] DEBUG  : [App] [Sources] [Subsonic - Navidrome] No new tracks discovered
[2024-06-25 17:27:34.759 +1000] DEBUG  : [App] [Sources] [Subsonic - Navidrome] [Player 1-matt] Started new Player listen range.
[2024-06-25 17:27:34.758 +1000] DEBUG  : [App] [Sources] [Subsonic - Navidrome] [Player 1-matt] New Play: (ec95a4ce8b8e8a0888eeaccb73529acd) The Wolfgang Press - The Wedding
[2024-06-25 17:27:34.749 +1000] DEBUG  : [App] [Sources] [Subsonic - Navidrome] Refreshing recently played
[2024-06-25 17:27:04.705 +1000] DEBUG  : [App] [Sources] [Subsonic - Navidrome] Last activity 2024-06-25T16:38:24+10:00 is 44 minutes outside of polling period (last activity + 300s) | Next check interval: (10 + 20)s
[2024-06-25 17:27:04.703 +1000] DEBUG  : [App] [Sources] [Subsonic - Navidrome] No new tracks discovered
```

**Versions (please complete the following information):**
- multi-scrobbler: 0.7.1 on Docker
- navidrome: 0.52.5 on Docker

**Additional context**

- I've confirmed the server on which the Docker container is running still has connectivity to the internet when this is happening.
- The docker container itself still has inbound connectivity because it is successfully polling Navidrome for the playing track.
- From inside the docker container (`docker compose exec -it multi-scrobbler /bin/bash`) I can ping the Navidrome container and I can ping IP addresses, eg. 8.8.8.8 - but I cannot ping domain names, eg. www.google.com
- Earlier today I was able to scrobble to both last.fm and listenbrainz, and the Multi-scrobbler container has not been changed, stopped or re-started since then.
- However after `docker compose down && docker compose up -d`, connectivity to both clients is resolved - with no additional changes to the server's internet connection or the docker network for my stack.
- At this point, I can ping www.google.com from within the container. 
- So the issue seems to be losing the ability to resolve DNS, and therefore possibly not a problem with the application itself...?

**Comment by FoxxMD** [comment]
Can you try using the [`foxxmd/multi-scrobbler:0.7.1-debian`](https://hub.docker.com/layers/foxxmd/multi-scrobbler/0.7.1-debian/images/sha256-9493ea4201086bd0089aa4319f424f31d5d322dd8fd27e2f92a621743ffaaf0b?context=repo) docker image?

**Comment by infinitejones** [comment]
No worries - thanks for Multi-scrobbler!

I've pulled the Debian image and re-started the container. If/when it fails again I'll post the same detail again here.

**Comment by infinitejones** [comment]
Following up on this - the container's been running with the Debian image since my last comment, with no problems at all. 

I occasionally see timeout errors for Listenbrainz in the log but I think that's the Listenbrainz API rather than the Multi Scrobbler. They don't prevent tracks being scrobbled correctly. 

(None visible in the log currently - I can post some in another issue if I see any again, if you want...?)

**Comment by FoxxMD** [comment]
That's likely the the LZ API. Glad the debian image has resolved the issue for you. I may be switching to use that image as the default in the near future since alpine seems to *still* have unresolved dns issues.

**Comment by infinitejones** [comment]
OK so after an unplanned container restart (due to a power cut), this happened again. This is using the Debian container.

Last.fm and Listenbrainz client tiles had ended up in the same state as my original screenshot and clicking the Start buttons didn't re-connect them. (Logs below.) Connected again automatically after `docker compose down && docker compose up`.

On attempting to re-auth with Last.fm, the callback URL ended up on a page saying `ETIMEDOUT - socket hang up`

On attempting to re-start Last.fm:

```[2024-07-05 15:45:50.267 +1000] WARN   : [App] [Scrobblers] [Lastfm - last.fm] Cannot start scrobble processing because auth test failed
[2024-07-05 15:45:50.263 +1000] ERROR  : [App] [Scrobblers] [Lastfm - last.fm] Authentication test failed! Due to a network issue. Will retry authentication on next heartbeat.
Error: Authentication test failed! Due to a network issue. Will retry authentication on next heartbeat.
    at LastfmScrobbler.testAuth (CWD/src/backend/scrobblers/AbstractScrobbleClient.ts:188:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at LastfmScrobbler.initScrobbleMonitoring (CWD/src/backend/scrobblers/AbstractScrobbleClient.ts:458:17)
    at <anonymous> (CWD/src/backend/server/api.ts:420:9)
    at async wrappedMiddleware (CWD/node_modules/@awaitjs/express/index.js:116:7)
caused by: Error: API call failed due -> API call timed out <- after max retries hit 2
    at LastfmApiClient.callApi (CWD/src/backend/common/vendor/LastfmApiClient.ts:133:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at LastfmApiClient.testAuth (CWD/src/backend/common/vendor/LastfmApiClient.ts:181:30)
    at LastfmScrobbler.doAuthentication (CWD/src/backend/scrobblers/LastfmScrobbler.ts:48:20)
    at LastfmScrobbler.testAuth (CWD/src/backend/scrobblers/AbstractScrobbleClient.ts:182:27)
    at LastfmScrobbler.initScrobbleMonitoring (CWD/src/backend/scrobblers/AbstractScrobbleClient.ts:458:17)
    at <anonymous> (CWD/src/backend/server/api.ts:420:9)
    at async wrappedMiddleware (CWD/node_modules/@awaitjs/express/index.js:116:7)
caused by: Error: ETIMEDOUT - socket hang up
    at ClientRequest.<anonymous> (CWD/node_modules/lastfm-node-client/lib/ApiRequest.js:119:26)
    at Object.onceWrapper (node:events:632:28)
    at ClientRequest.emit (node:events:518:28)
    at ClientRequest.emit (node:domain:488:12)
    at TLSSocket.emitRequestTimeout (node:_http_client:840:9)
    at Object.onceWrapper (node:events:632:28)
    at TLSSocket.emit (node:events:530:35)
    at TLSSocket.emit (node:domain:488:12)
    at Socket._onTimeout (node:net:589:8)
    at listOnTimeout (node:internal/timers:573:17)
[2024-07-05 15:45:50.260 +1000] ERROR  : [App] [Scrobblers] [API - Lastfm - last.fm] Testing auth failed
[2024-07-05 15:45:42.250 +1000] WARN   : [App] [Scrobblers] [API - Lastfm - last.fm] API call failed due to network issue (request timed out after 3 seconds), retrying in 3 seconds...
[2024-07-05 15:45:35.745 +1000] WARN   : [App] [Scrobblers] [API - Lastfm - last.fm] API call failed due to network issue (request timed out after 3 seconds), retrying in 1.5 seconds...
[2024-07-05 15:45:30.741 +1000] INFO   : [App] [Scrobblers] [Lastfm - last.fm] Trying to start scrobbler...
[2024-07-05 15:45:30.739 +1000] WARN   : [App] [Scrobblers] [Lastfm - last.fm] Polling is already stopped!
[2024-07-05 15:45:30.738 +1000] INFO   : [App] [Scrobblers] [Lastfm - last.fm] Checking (and trying) to stop scrobbler if already running...
```

On attempting to re-start Listenbrainz:

```[2024-07-05 15:41:58.968 +1000] ERROR  : [App] [Scrobblers] [Listenbrainz - Listenbrainz] Could not communicate with Listenbrainz API
[2024-07-05 15:41:48.586 +1000] INFO   : [App] [Scrobblers] [Listenbrainz - Listenbrainz] Trying to start scrobbler...
[2024-07-05 15:41:48.584 +1000] WARN   : [App] [Scrobblers] [Listenbrainz - Listenbrainz] Polling is already stopped!
[2024-07-05 15:41:48.582 +1000] INFO   : [App] [Scrobblers] [Listenbrainz - Listenbrainz] Checking (and trying) to stop scrobbler if already running...
[2024-07-05 15:41:34.950 +1000] INFO   : [App] [Scrobblers] [Listenbrainz - Listenbrainz] Trying to start scrobbler...
[2024-07-05 15:41:34.949 +1000] WARN   : [App] [Scrobblers] [Listenbrainz - Listenbrainz] Polling is already stopped!
[2024-07-05 15:41:34.947 +1000] INFO   : [App] [Scrobblers] [Listenbrainz - Listenbrainz] Checking (and trying) to stop scrobbler if already running...
[2024-07-05 15:41:14.993 +1000] WARN   : [App] [Scrobblers] [Listenbrainz - Listenbrainz] Cannot start scrobble processing because auth test failed
[2024-07-05 15:41:14.991 +1000] ERROR  : [App] [Scrobblers] [Listenbrainz - Listenbrainz] Authentication test failed! Due to a network issue. Will retry authentication on next heartbeat.
Error: Authentication test failed! Due to a network issue. Will retry authentication on next heartbeat.
    at ListenbrainzScrobbler.testAuth (CWD/src/backend/scrobblers/AbstractScrobbleClient.ts:188:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ListenbrainzScrobbler.initScrobbleMonitoring (CWD/src/backend/scrobblers/AbstractScrobbleClient.ts:458:17)
    at <anonymous> (CWD/src/backend/server/api.ts:420:9)
    at async wrappedMiddleware (CWD/node_modules/@awaitjs/express/index.js:116:7)
caused by: Error: getaddrinfo EAI_AGAIN api.listenbrainz.org
    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)
    at __node_internal_ (node:internal/errors:782:10)
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)
[2024-07-05 15:41:14.989 +1000] ERROR  : [App] [Scrobblers] [Listenbrainz - Listenbrainz] Could not communicate with Listenbrainz API
```

**Comment by FoxxMD** [comment]
Thanks for the logs. Both of these errors are related to (upstream of the container) network connectivity. [`ETIMEOUT`](https://www.man7.org/linux/man-pages/man3/errno.3.html) means it could not connect to the LFM server. `EAI_AGAIN` means it failed to lookup DNS info for the LZ domain name.

The debian image has solved this issue _when it's intermittent but consistent_ but your issue seems to be rarer than those. I'm not ruling out it being an image issue but the fact that `compose down/up` fixes things leads me to believe it's not specifically an issue with MS or the docker container but rather something with your network topology:

* Does your docker daemon/network run using a network driver other than [`bridge`](https://docs.docker.com/network/drivers/bridge/)?
* Is MS part of a custom docker network (specified in a compose file or otherwise?)
* Does your host network have and DNS caching or self-hosted DNS solution such as pi-hole?

**Comment by infinitejones** [comment]
Aaaah OK - yes, I run pi-hole on another machine - so I suspect it might be as simple as the container coming back up and attempting to connect after the power cut, before the pi-hole machine was back up, and/or before my modem/router had had chance to re-connect to the Internet. I just did a "controlled" power cut/restart and the same thing happened.

Until then, the Debian container had run flawlessly for over a week.

Thank you!

**Comment by FoxxMD** [comment]
I'll leave this open for now, just in case, and check back in in a week or so to see if the debian image is still working as expected for you.

**Comment by FoxxMD** [comment]
@infinitejones how has the container stability been for you this last week?

**Comment by infinitejones** [comment]
All good, no problems at all. This is using `latest` so it's the Debian base image. Thanks very much!

**Comment by cairobraga** [comment]
sorry to ressuscitate this @FoxxMD, but I'm having the same issue and I've tried restarting the container, I've tried changing the DNS server of my internet connection, updated the container image and I'm still getting this:

`multi-scrobbler is starting!
[ls.io-init] done.
[2025-01-12 19:07:41.778 +0000] VERBOSE: [Init] Config Dir ENV: /config -> Resolved: /config
[2025-01-12 19:07:42.165 +0000] INFO   : [Init] Version: master-e80ad81
[2025-01-12 19:07:42.166 +0000] INFO   : [Init] Generating schema definitions...
[2025-01-12 19:07:50.679 +0000] INFO   : [Init] Schema definitions generated
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
7:07:50 PM [vite-express] Running in production mode
7:07:50 PM [vite-express] Inline config detected, ignoring Vite config file
7:07:50 PM [vite-express] Serving static files from /app/dist
[2025-01-12 19:07:50.769 +0000] INFO   : [App] [API] Server started:
---> Local          http://localhost:9078
---> Network        http://172.17.0.11:9078
---> Network (IPv6) http://[::1]:9078
--- HINT ---
MS is likely being run in a container with BRIDGE networking which means the above addresses are not accessible from outside this container.
To ensure the container is accessible make sure you have mapped the *container* port 9078 to a *host* port. https://foxxmd.github.io/multi-scrobbler/docs/installation#networking
The container will then be accessible at http://HOST_MACHINE_IP:HOST_PORT
--- HINT ---
[2025-01-12 19:07:51.878 +0000] DEBUG  : [App] [Scrobblers] Constructing maloja (cairobragaMaloja) client...
[2025-01-12 19:07:51.880 +0000] INFO   : [App] [Scrobblers] [Maloja - cairobragaMaloja] Client Added
[2025-01-12 19:07:51.881 +0000] INFO   : [App] Starting scrobble clients...
[2025-01-12 19:07:51.882 +0000] DEBUG  : [App] [Scrobblers] [Maloja - cairobragaMaloja] Attempting to initialize...
[2025-01-12 19:07:51.883 +0000] VERBOSE: [App] [Scrobblers] [Maloja - cairobragaMaloja] Building required data init succeeded
[2025-01-12 19:07:57.490 +0000] INFO   : [App] [Scrobblers] [Maloja - cairobragaMaloja] Communication test succeeded.
[2025-01-12 19:07:57.491 +0000] INFO   : [App] [Scrobblers] [Maloja - cairobragaMaloja] Maloja Server Version: 3.2.2
[2025-01-12 19:08:02.624 +0000] VERBOSE: [App] [Scrobblers] [Maloja - cairobragaMaloja] Connection check succeeded
[2025-01-12 19:08:07.736 +0000] INFO   : [App] [Scrobblers] [Maloja - cairobragaMaloja] Auth test passed!
[2025-01-12 19:08:07.737 +0000] INFO   : [App] [Scrobblers] [Maloja - cairobragaMaloja] Fully Initialized!
[2025-01-12 19:08:07.737 +0000] VERBOSE: [App] [Scrobblers] [Maloja - cairobragaMaloja] Fetching up to 100 initial scrobbles...
[2025-01-12 19:08:07.738 +0000] DEBUG  : [App] [Scrobblers] [Maloja - cairobragaMaloja] Refreshing recent scrobbles
[2025-01-12 19:08:13.371 +0000] DEBUG  : [App] [Scrobblers] [Maloja - cairobragaMaloja] Found 100 recent scrobbles
[2025-01-12 19:08:13.374 +0000] INFO   : [App] [Scrobblers] [Maloja - cairobragaMaloja] Scrobble processing started
[2025-01-12 19:08:14.060 +0000] DEBUG  : [App] [Sources] (cairobragaLFM_s) Constructing lastfm source
[2025-01-12 19:08:14.062 +0000] INFO   : [App] [Sources] [Lastfm - cairobragaLFM_s] Note: The player for this source is an analogue for the 'Now Playing' status exposed by lastfm which is NOT used for scrobbling. Instead, the 'recently played' or 'history' information provided by this source is used for scrobbles.
[2025-01-12 19:08:14.063 +0000] DEBUG  : [App] [Sources] (cairobragaSpotify) Constructing spotify source
[2025-01-12 19:08:14.064 +0000] DEBUG  : [App] [Sources] [Lastfm - cairobragaLFM_s] Attempting to initialize...
[2025-01-12 19:08:14.065 +0000] VERBOSE: [App] [Sources] [Lastfm - cairobragaLFM_s] Building required data init succeeded
[2025-01-12 19:08:19.206 +0000] VERBOSE: [App] [Sources] [Lastfm - cairobragaLFM_s] Connection check succeeded
[2025-01-12 19:08:24.211 +0000] WARN   : [App] [Sources] [Lastfm - cairobragaLFM_s] [API - Lastfm - cairobragaLFM_s] API call failed due to network issue (request timed out after 3 seconds), retrying in 1.5 seconds...
[2025-01-12 19:08:30.714 +0000] WARN   : [App] [Sources] [Lastfm - cairobragaLFM_s] [API - Lastfm - cairobragaLFM_s] API call failed due to network issue (request timed out after 3 seconds), retrying in 3 seconds...
[2025-01-12 19:08:38.718 +0000] ERROR  : [App] [Sources] [Lastfm - cairobragaLFM_s] [API - Lastfm - cairobragaLFM_s] Testing auth failed
[2025-01-12 19:08:38.719 +0000] ERROR  : [App] [Sources] [Lastfm - cairobragaLFM_s] Authentication test failed! Due to a network issue. Will retry authentication on next heartbeat.
Error: Authentication test failed! Due to a network issue. Will retry authentication on next heartbeat.
    at LastfmSource.testAuth (CWD/src/backend/common/AbstractComponent.ts:235:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at LastfmSource.initialize (CWD/src/backend/common/AbstractComponent.ts:56:13)
    at <anonymous> (CWD/src/backend/index.ts:124:17)
caused by: Error: API call failed due -> API call timed out <- after max retries hit 2
    at LastfmApiClient.callApi (CWD/src/backend/common/vendor/LastfmApiClient.ts:133:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at LastfmApiClient.testAuth (CWD/src/backend/common/vendor/LastfmApiClient.ts:181:30)
    at LastfmSource.doAuthentication (CWD/src/backend/sources/LastfmSource.ts:65:20)
    at LastfmSource.testAuth (CWD/src/backend/common/AbstractComponent.ts:229:27)
    at LastfmSource.initialize (CWD/src/backend/common/AbstractComponent.ts:56:13)
    at <anonymous> (CWD/src/backend/index.ts:124:17)
caused by: Error: ETIMEDOUT - socket hang up
    at ClientRequest.<anonymous> (CWD/node_modules/lastfm-node-client/lib/ApiRequest.js:119:26)
    at Object.onceWrapper (node:events:632:28)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.emitRequestTimeout (node:_http_client:840:9)
    at Object.onceWrapper (node:events:632:28)
    at TLSSocket.emit (node:events:530:35)
    at Socket._onTimeout (node:net:589:8)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
[2025-01-12 19:08:38.725 +0000] INFO   : [App] [Sources] [Lastfm - cairobragaLFM_s] Fully Initialized!
[2025-01-12 19:08:38.728 +0000] DEBUG  : [App] [Sources] [Spotify - cairobragaSpotify] Attempting to initialize...
[2025-01-12 19:08:38.731 +0000] VERBOSE: [App] [Sources] [Spotify - cairobragaSpotify] Building required data init succeeded
[2025-01-12 19:08:44.213 +0000] VERBOSE: [App] [Sources] [Spotify - cairobragaSpotify] Connection check succeeded
[2025-01-12 19:08:49.334 +0000] INFO   : [App] [Sources] [Spotify - cairobragaSpotify] Fully Initialized!
[2025-01-12 19:08:49.334 +0000] INFO   : [App] [Sources] Finished initializing sources
[2025-01-12 19:08:52.337 +0000] INFO   : [App] Some sources are not ready, open the dashboard to continue
[2025-01-12 19:08:52.339 +0000] INFO   : [App] Scheduler started.
`

"ETIMEDOUT - socket hang up" is also what appears when I try to reauthenticate via the web interface, in the callback page.

I'm at my wit's end with this, don't know what to do.

**Comment by FoxxMD** [comment]
Hi @cairobraga do any of the questions [from this comment above](https://github.com/FoxxMD/multi-scrobbler/issues/160#issuecomment-2214345114) apply to you?

> * Does your docker daemon/network run using a network driver other than [`bridge`](https://docs.docker.com/network/drivers/bridge/)?
> * Is MS part of a custom docker network (specified in a compose file or otherwise?) or otherwise have DNS managed by [a container like dnsmasq?](https://computingforgeeks.com/run-and-use-dnsmasq-in-docker-container/)
> * Does your host machine have DNS caching (like `dnsmasq`) or host network use a self-hosted DNS solution such as pi-hole?

And can you confirm what version of MS in docker you are running?

**Comment by FoxxMD** [comment]
It's interesting that the connection check is fine but the auth call is timing out since they both use the same endpoint. The original problem for this issue was DNS related but your problem is with not receiving a response back from the server (not DNS). That makes me think there is an issue with your apikey or LFM responding to an authorized call, rather than an issue with MS specifically.

You can check to see if LFM responds normally within the docker container by exec'ing in and trying to make a curl GET call. A normal response would be a 400 bad request with html. If you get the same result (normal OR timeout) doing a curl from the host machine then it's probably not an issue with docker.

```
docker container exec -it [containerName] /bin/sh
curl -v http://ws.audioscrobbler.com/2.0/
```

You could also try [running multi-scrobbler without docker](https://foxxmd.github.io/multi-scrobbler/docs/installation/#local-installation) to see if that makes a difference.

**Comment by cairobraga** [comment]
Hi, @FoxxMD, sorry for the superlate response.

I did the DNS testing and as soon as I deactivated Cloudflare DNS on my network, the LastFM connection worked. I also tested with Quad9 and it also worked. I would assume it was a temporary DNS issue, I haven't had this issue since.

So, yeah, not a multi-scrobbler issue at all. Thanks for your attention and help, and for this amazing software!
