### ISSUE TITLE
TLS error trying to connect to Maloja

### ISSUE THREAD

**Issue by Karsten-Yan** [FoxxMD/multi-scrobbler#176]
I don't know if this is even something on the Multiscrobbler side, so if not feel free to close this issue.

**Describe the bug**
Recently i upgraded my installation on my raspberry pi (using multiscrobbler together with maloja) from 32bit to 64bit and I am now using the most recent stable docker images of those two services. This means i now upgraded maloja from 3.1.5 to 3.2.2 and multiscrobbler from the last version that still supported 32bit to the latest one. 

Additionally i have all my docker containers directly connected into my tailnet via tailscale (this means in my cases the urls the services use are https://scrobbler.<tailnetid>.ts.net for multiscrobbler and https://music-tracker.<tailnetid>.ts.net for maloja). Now multiscrobbler can not connect to maloja because of a TLS error (detailed in the logs below). This used to work before using the same setup. I am also using the direct copies of the configs and certificates as before. Everything seems to work so far on the multiscrobbler side (i can access the web ui, spotify and jellyfin sources also seem to work).

Do i need to change some config in multiscrobbler or is this outside of your scope (as the error implies an error in TLS validation which is handled by tailscale)? Just thought it was odd, since it used to work before using exactly the same setup. 

**Logs**
```
multiscrobbler  | Error: Initialization failed
multiscrobbler  |     at MalojaScrobbler.initialize (CWD/src/backend/common/AbstractComponent.ts:33:31)
multiscrobbler  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
multiscrobbler  |     at MalojaScrobbler.initScrobbleMonitoring (CWD/src/backend/scrobblers/AbstractScrobbleClient.ts:407:18)
multiscrobbler  |     at <anonymous> (CWD/src/backend/server/api.ts:425:9)
multiscrobbler  |     at async wrappedMiddleware (CWD/node_modules/@awaitjs/express/index.js:116:7)
multiscrobbler  | caused by: Error: Communicating with upstream service failed
multiscrobbler  |     at MalojaScrobbler.checkConnection (CWD/src/backend/common/AbstractComponent.ts:91:19)
multiscrobbler  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
multiscrobbler  |     at MalojaScrobbler.initialize (CWD/src/backend/common/AbstractComponent.ts:23:13)
multiscrobbler  |     at MalojaScrobbler.initScrobbleMonitoring (CWD/src/backend/scrobblers/AbstractScrobbleClient.ts:407:18)
multiscrobbler  |     at <anonymous> (CWD/src/backend/server/api.ts:425:9)
multiscrobbler  |     at async wrappedMiddleware (CWD/node_modules/@awaitjs/express/index.js:116:7)
multiscrobbler  | caused by: Error: Communication test failed
multiscrobbler  |     at MalojaScrobbler.testConnection (CWD/src/backend/scrobblers/MalojaScrobbler.ts:200:19)
multiscrobbler  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
multiscrobbler  |     at MalojaScrobbler.doCheckConnection (CWD/src/backend/scrobblers/MalojaScrobbler.ts:252:9)
multiscrobbler  |     at MalojaScrobbler.checkConnection (CWD/src/backend/common/AbstractComponent.ts:78:25)
multiscrobbler  |     at MalojaScrobbler.initialize (CWD/src/backend/common/AbstractComponent.ts:23:13)
multiscrobbler  |     at MalojaScrobbler.initScrobbleMonitoring (CWD/src/backend/scrobblers/AbstractScrobbleClient.ts:407:18)
multiscrobbler  |     at <anonymous> (CWD/src/backend/server/api.ts:425:9)
multiscrobbler  |     at async wrappedMiddleware (CWD/node_modules/@awaitjs/express/index.js:116:7)
multiscrobbler  | caused by: Error: Unexpected error occurred during API call
multiscrobbler  |     at MalojaScrobbler.callApi (CWD/src/backend/scrobblers/MalojaScrobbler.ts:163:23)
multiscrobbler  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
multiscrobbler  |     at MalojaScrobbler.testConnection (CWD/src/backend/scrobblers/MalojaScrobbler.ts:172:36)
multiscrobbler  |     at MalojaScrobbler.doCheckConnection (CWD/src/backend/scrobblers/MalojaScrobbler.ts:252:9)
multiscrobbler  |     at MalojaScrobbler.checkConnection (CWD/src/backend/common/AbstractComponent.ts:78:25)
multiscrobbler  |     at MalojaScrobbler.initialize (CWD/src/backend/common/AbstractComponent.ts:23:13)
multiscrobbler  |     at MalojaScrobbler.initScrobbleMonitoring (CWD/src/backend/scrobblers/AbstractScrobbleClient.ts:407:18)
multiscrobbler  |     at <anonymous> (CWD/src/backend/server/api.ts:425:9)
multiscrobbler  |     at async wrappedMiddleware (CWD/node_modules/@awaitjs/express/index.js:116:7)
multiscrobbler  | caused by: Error: Client network socket disconnected before secure TLS connection was established
multiscrobbler  |     at connResetException (node:internal/errors:787:14)
multiscrobbler  |     at TLSSocket.onConnectEnd (node:_tls_wrap:1727:19)
multiscrobbler  |     at TLSSocket.emit (node:events:530:35)
multiscrobbler  |     at endReadableNT (node:internal/streams/readable:1696:12)
multiscrobbler  |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by Karsten-Yan** [comment]
Huh okay, this was weird. After a restart of the raspberry pi and restart of the containers it now works ...

I'll close the issue now, sorry to bother you :)

**Comment by FoxxMD** [comment]
This is anecdotal but I find that docker networking doesn't reflect changes on the host-level if the container is already started. That is, if the container is running and then you connect to a VPN or tailscale and DNS changes at the host level docker containers don't get these changes "downstream" or w/e. 
I usually have to restart containers or have all host-level networking done before starting containers.
