### ISSUE TITLE
bug: YT Music authentication test failed

### ISSUE THREAD

**Issue by UditDey** [FoxxMD/multi-scrobbler#229]
### Please check existing knowledge before opening an issue

- [X] I have [checked the FAQ](https://foxxmd.github.io/multi-scrobbler/docs/FAQ/) and [documentation](https://foxxmd.github.io/multi-scrobbler/docs/configuration/)
- [X] I have [searched through existing issues](https://github.com/FoxxMD/multi-scrobbler/issues?q=sort%3Aupdated-desc) and [discussions.](https://github.com/FoxxMD/multi-scrobbler/discussions)

### Describe the Bug

I recently started using multi-scrobbler with the pr-203 docker image for YT Music scrobbling. It worked fine for the first week but I just noticed it hasn't been scrobbling tracks for the past 3 days. Opening the dashboard shows this:

```
[2024-11-14 09:26:17.738 +0000] ERROR  : [App] [Sources] [Ytmusic - MyYTMusic] Authentication test failed!
Error: Authentication test failed!
    at YTMusicSource.testAuth (CWD/src/backend/common/AbstractComponent.ts:235:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at YTMusicSource.initialize (CWD/src/backend/common/AbstractComponent.ts:56:13)
    at <anonymous> (CWD/src/backend/index.ts:124:17)
caused by: Error: Credentials exist but API calls are failing. Try re-authenticating?
    at YTMusicSource.doAuthentication (CWD/src/backend/sources/YTMusicSource.ts:155:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at YTMusicSource.testAuth (CWD/src/backend/common/AbstractComponent.ts:229:27)
    at YTMusicSource.initialize (CWD/src/backend/common/AbstractComponent.ts:56:13)
    at <anonymous> (CWD/src/backend/index.ts:124:17)
caused by: Error: Request to https://www.youtube.com/youtubei/v1/account/accounts_list?prettyPrint=false&alt=json failed with status 400
    at HTTPClient.fetch (file://CWD/node_modules/youtubei.js/dist/src/utils/HTTPClient.js:117:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Actions.execute (file://CWD/node_modules/youtubei.js/dist/src/core/Actions.js:66:26)
    at async AccountManager.getInfo (file://CWD/node_modules/youtubei.js/dist/src/core/managers/AccountManager.js:49:26)
    at YTMusicSource.doAuthentication (CWD/src/backend/sources/YTMusicSource.ts:149:17)
    at YTMusicSource.testAuth (CWD/src/backend/common/AbstractComponent.ts:229:27)
    at YTMusicSource.initialize (CWD/src/backend/common/AbstractComponent.ts:56:13)
    at <anonymous> (CWD/src/backend/index.ts:124:17)
[2024-11-14 09:26:17.736 +0000] ERROR  : [App] [Sources] [Ytmusic - MyYTMusic] Additional API response details
    error: {
      "code": 400,
      "message": "Request contains an invalid argument.",
      "status": "INVALID_ARGUMENT"
    }
```

I've tried reauthenticating and even restarting the whole container but no luck. Upon reauthentication, I enter the code into the google page, the dashboard even says `DEBUG  : [App] [Sources] [Ytmusic - MyYTMusic] Auth success` but the source still remains "idle" and clicking on start results in the output I pasted above

### Platform

Docker

### Versions

multi-scrobbler:pr-203 Docker image on Ubuntu

**Comment by roos-robert** [comment]
It could very well be related to this: https://github.com/sigma67/ytmusicapi/issues/676 I'm facing the same issue using oauth.

**Comment by UditDey** [comment]
Yes, looks like it. Youtube must have changed the endpoint. oauth itself seems to be working, its just the `https://www.youtube.com/youtubei/v1/account/accounts_list?prettyPrint=false&alt=json` request that is failing

**Comment by tylermiranda** [comment]
yep, can confirm, having the same issue

**Comment by FoxxMD** [comment]
YTM is really throwing wrenches in the gears :upside_down_face: I hope this isn't an effort on their part to block unofficial usage but rather a side effect of regular development evolution but who knows.

I am on semi-vacation for at the moment and will have more time to focus on this at the end of the month or December.

**Comment by UditDey** [comment]
I have a hunch this is just a change and not an effort to block us. Also take your time lol, FWIW, I've been using the unofficial YTM desktop app and that has a scrobbling plugin, which is good enough for now.

**Comment by FoxxMD** [comment]
For everyone having auth and history fetching issues: please try out the new authentication methods detailed in [#236](https://github.com/FoxxMD/multi-scrobbler/pull/236#issuecomment-2515572189) using the docker image `foxxmd/multi-scrobbler:pr-236`

If you try out the new docker image please post any issues you have with it in the issue for #236 instead of this one so I can better keep track of things, thanks.

**Comment by FoxxMD** [comment]
Fixed in [v0.9.0](https://github.com/FoxxMD/multi-scrobbler/releases/tag/0.9.0)
