### ISSUE TITLE
bug: Missing scrobbles with Jellyfin.

### ISSUE THREAD

**Issue by xGigaa** [FoxxMD/multi-scrobbler#239]
### Please check existing knowledge before opening an issue

- [X] I have [checked the FAQ](https://foxxmd.github.io/multi-scrobbler/docs/FAQ/) and [documentation](https://foxxmd.github.io/multi-scrobbler/docs/configuration/)
- [X] I have [searched through existing issues](https://github.com/FoxxMD/multi-scrobbler/issues?q=sort%3Aupdated-desc) and [discussions.](https://github.com/FoxxMD/multi-scrobbler/discussions)

### Describe the Bug

For some reason it seems like scrobbles are getting missed from time to time.
I played a full album through and only the first song got picked up but the rest got ignored.
And you can see in the log I'm getting this "Cannot use 'in' operator to search for 'data' in undefined" error.
Maybe I'm doing something wrong here?

### Platform

Docker

### Versions

- multi-scrobbler 0.8.8 on docker
- Jellyfin 10.10.3

### Logs

```shell
[2024-12-14 09:09:38.537 +0100] ERROR  : [App] [Sources] [Jellyfin - unnamed] Error occurred while polling
[2024-12-14 09:09:38.510 +0100] INFO   : [App] [Sources] [Jellyfin - unnamed] Polling started
[2024-12-14 09:09:22.508 +0100] INFO   : [App] [Sources] [Jellyfin - unnamed] Poll retries (2) less than max poll retries (5), restarting polling after 16 second delay...
[2024-12-14 09:09:22.506 +0100] ERROR  : [App] [Sources] [Jellyfin - unnamed] Cannot use 'in' operator to search for 'data' in undefined
TypeError: Cannot use 'in' operator to search for 'data' in undefined
    at isPlayObject (CWD/src/core/Atomic.ts:178:11)
    at asPlayerStateData (CWD/src/backend/common/infrastructure/Atomic.ts:127:127)
    at PositionalPlayerState.update (CWD/src/backend/sources/PlayerState/AbstractPlayerState.ts:136:13)
    at JellyfinApiSource.processRecentPlays (CWD/src/backend/sources/MemorySource.ts:184:53)
    at JellyfinApiSource.getRecentlyPlayed (CWD/src/backend/sources/JellyfinApiSource.ts:430:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at JellyfinApiSource.doPolling (CWD/src/backend/sources/AbstractSource.ts:389:34)
    at JellyfinApiSource.startPolling (CWD/src/backend/sources/AbstractSource.ts:324:27)
    at JellyfinApiSource.poll (CWD/src/backend/sources/AbstractSource.ts:292:9)
[2024-12-14 09:09:22.505 +0100] ERROR  : [App] [Sources] [Jellyfin - unnamed] Error occurred while polling
[2024-12-14 09:09:22.483 +0100] INFO   : [App] [Sources] [Jellyfin - unnamed] Polling started
[2024-12-14 09:09:15.480 +0100] INFO   : [App] [Sources] [Jellyfin - unnamed] Poll retries (1) less than max poll retries (5), restarting polling after 7 second delay...
[2024-12-14 09:09:15.478 +0100] ERROR  : [App] [Sources] [Jellyfin - unnamed] Cannot use 'in' operator to search for 'data' in undefined
TypeError: Cannot use 'in' operator to search for 'data' in undefined
    at isPlayObject (CWD/src/core/Atomic.ts:178:11)
    at asPlayerStateData (CWD/src/backend/common/infrastructure/Atomic.ts:127:127)
    at PositionalPlayerState.update (CWD/src/backend/sources/PlayerState/AbstractPlayerState.ts:136:13)
    at JellyfinApiSource.processRecentPlays (CWD/src/backend/sources/MemorySource.ts:184:53)
    at JellyfinApiSource.getRecentlyPlayed (CWD/src/backend/sources/JellyfinApiSource.ts:430:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at JellyfinApiSource.doPolling (CWD/src/backend/sources/AbstractSource.ts:389:34)
    at JellyfinApiSource.startPolling (CWD/src/backend/sources/AbstractSource.ts:324:27)
    at JellyfinApiSource.poll (CWD/src/backend/sources/AbstractSource.ts:292:9)
[2024-12-14 09:09:15.477 +0100] ERROR  : [App] [Sources] [Jellyfin - unnamed] Error occurred while polling
[2024-12-14 08:55:32.206 +0100] VERBOSE: [App] [Sources] [Jellyfin - unnamed] [Player 3rzZ6jIkak-Desktop Client-Feishin-gigaa] (e1416353dceb4b508238297075ae533d) Dopelord - Green Plague not added because did not meet thresholds with tracked time of 122.04s (wanted 240s) and tracked percent of 27.00% (wanted 50%).
[2024-12-14 08:55:32.203 +0100] VERBOSE: [App] [Sources] [Jellyfin - unnamed] [Player 3rzZ6jIkak-Desktop Client-Feishin-gigaa] New Play: (81629471caec053a462eb090f350277c) Dopelord - Pass the Bong
[2024-12-14 08:55:32.190 +0100] INFO   : [App] [Sources] [Jellyfin - unnamed] Polling started
[2024-12-14 08:55:28.191 +0100] INFO   : [App] [Sources] [Jellyfin - unnamed] Poll retries (0) less than max poll retries (5), restarting polling after 4 second delay...
[2024-12-14 08:55:28.188 +0100] ERROR  : [App] [Sources] [Jellyfin - unnamed] Cannot use 'in' operator to search for 'data' in undefined
TypeError: Cannot use 'in' operator to search for 'data' in undefined
    at isPlayObject (CWD/src/core/Atomic.ts:178:11)
    at asPlayerStateData (CWD/src/backend/common/infrastructure/Atomic.ts:127:127)
    at PositionalPlayerState.update (CWD/src/backend/sources/PlayerState/AbstractPlayerState.ts:136:13)
    at JellyfinApiSource.processRecentPlays (CWD/src/backend/sources/MemorySource.ts:184:53)
    at JellyfinApiSource.getRecentlyPlayed (CWD/src/backend/sources/JellyfinApiSource.ts:430:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at JellyfinApiSource.doPolling (CWD/src/backend/sources/AbstractSource.ts:389:34)
    at JellyfinApiSource.startPolling (CWD/src/backend/sources/AbstractSource.ts:324:27)
    at JellyfinApiSource.poll (CWD/src/backend/sources/AbstractSource.ts:292:9)
[2024-12-14 08:55:28.188 +0100] ERROR  : [App] [Sources] [Jellyfin - unnamed] Error occurred while polling
[2024-12-14 08:53:27.196 +0100] VERBOSE: [App] [Sources] [Jellyfin - unnamed] [Player 3rzZ6jIkak-Desktop Client-Feishin-gigaa] New Play: (e1416353dceb4b508238297075ae533d) Dopelord - Green Plague
[2024-12-14 08:53:27.179 +0100] INFO   : [App] [Sources] [Jellyfin - unnamed] Polling started
[2024-12-14 08:53:27.002 +0100] VERBOSE: [App] [Heartbeat] [Clients] Checked Dead letter queue for 2 clients.
[2024-12-14 08:53:26.999 +0100] VERBOSE: [App] [Heartbeat] [Clients] Starting check...
[2024-12-14 08:53:26.998 +0100] INFO   : [App] [Heartbeat] [Sources] Attempted to restart 1 sources that were not polling.
[2024-12-14 08:53:26.997 +0100] VERBOSE: [App] [Heartbeat] [Sources] Checked 1 sources for restart signals.
[2024-12-14 08:53:26.988 +0100] INFO   : [App] [Sources] [Jellyfin - unnamed] Should be polling! Attempting to restart polling...
[2024-12-14 08:53:26.983 +0100] VERBOSE: [App] [Heartbeat] [Sources] Starting check...
[2024-12-14 08:40:20.776 +0100] WARN   : [App] [Sources] [Jellyfin - unnamed] Poll retries (5) equal to max poll retries (5), stopping polling!
[2024-12-14 08:40:20.776 +0100] ERROR  : [App] [Sources] [Jellyfin - unnamed] Cannot use 'in' operator to search for 'data' in undefined
TypeError: Cannot use 'in' operator to search for 'data' in undefined
    at isPlayObject (CWD/src/core/Atomic.ts:178:11)
    at asPlayerStateData (CWD/src/backend/common/infrastructure/Atomic.ts:127:127)
    at PositionalPlayerState.update (CWD/src/backend/sources/PlayerState/AbstractPlayerState.ts:136:13)
    at JellyfinApiSource.processRecentPlays (CWD/src/backend/sources/MemorySource.ts:184:53)
    at JellyfinApiSource.getRecentlyPlayed (CWD/src/backend/sources/JellyfinApiSource.ts:430:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at JellyfinApiSource.doPolling (CWD/src/backend/sources/AbstractSource.ts:389:34)
    at JellyfinApiSource.startPolling (CWD/src/backend/sources/AbstractSource.ts:324:27)
    at JellyfinApiSource.poll (CWD/src/backend/sources/AbstractSource.ts:292:9)
[2024-12-14 08:40:20.775 +0100] ERROR  : [App] [Sources] [Jellyfin - unnamed] Error occurred while polling
[2024-12-14 08:33:26.989 +0100] VERBOSE: [App] [Heartbeat] [Clients] Checked Dead letter queue for 2 clients.
[2024-12-14 08:33:26.989 +0100] VERBOSE: [App] [Heartbeat] [Clients] Starting check...
[2024-12-14 08:33:26.982 +0100] VERBOSE: [App] [Heartbeat] [Sources] Checked 1 sources for restart signals.
[2024-12-14 08:33:26.982 +0100] VERBOSE: [App] [Heartbeat] [Sources] Starting check...
[2024-12-14 08:32:33.384 +0100] INFO   : [App] [Scrobblers] [Lastfm - unnamed-lfm] Scrobbled (Backlog) => (Jellyfin) Dopelord - Addicted to Black Magick @ 2024-12-14T08:26:34+01:00 (S)
[2024-12-14 08:32:32.555 +0100] INFO   : [App] [Scrobblers] [Maloja - unnamed-mlj] Scrobbled (Backlog)     => (Jellyfin) Dopelord - Addicted to Black Magick @ 2024-12-14T08:26:34+01:00 (S)
[2024-12-14 08:32:32.163 +0100] INFO   : [App] [Sources] [Jellyfin - unnamed] Discovered => Dopelord - Addicted to Black Magick @ 2024-12-14T08:26:34+01:00 (S)
[2024-12-14 08:32:32.155 +0100] VERBOSE: [App] [Sources] [Jellyfin - unnamed] [Player 3rzZ6jIkak-Desktop Client-Feishin-gigaa] (3e2d9d0bab094c07176104398536df05) Dopelord - Addicted to Black Magick added after met thresholds with tracked time of 290.92s (wanted 240s) and tracked percent of 98.00% (wanted 50%) and not matching any prior plays
[2024-12-14 08:32:32.154 +0100] VERBOSE: [App] [Sources] [Jellyfin - unnamed] [Player 3rzZ6jIkak-Desktop Client-Feishin-gigaa] New Play: (6bbde4b7b5f9dc845beba88a68e97c5a) Dopelord - Preacher Electrick
[2024-12-14 08:32:32.119 +0100] INFO   : [App] [Sources] [Jellyfin - unnamed] Polling started
[2024-12-14 08:31:28.119 +0100] INFO   : [App] [Sources] [Jellyfin - unnamed] Poll retries (4) less than max poll retries (5), restarting polling after 64 second delay...
[2024-12-14 08:31:28.118 +0100] ERROR  : [App] [Sources] [Jellyfin - unnamed] Cannot use 'in' operator to search for 'data' in undefined
TypeError: Cannot use 'in' operator to search for 'data' in undefined
```

**Comment by FoxxMD** [comment]
This should be fixed in the newest `foxxmd/multi-scrobbler:edge` docker image. Please try it out and let me know if it's fixed your issue.

**Comment by xGigaa** [comment]
Just tested it with a few albums. 
Seems like that did the trick. :)
Thanks!

**Comment by FoxxMD** [comment]
Fixed in [v0.9.0](https://github.com/FoxxMD/multi-scrobbler/releases/tag/0.9.0)
