### ISSUE TITLE
bug: Tracks with Album Artist as "Various Artists" from Plex are failing to scrobble

### ISSUE THREAD

**Issue by captainnapalm** [FoxxMD/multi-scrobbler#241]
### Please check existing knowledge before opening an issue

- [X] I have [checked the FAQ](https://foxxmd.github.io/multi-scrobbler/docs/FAQ/) and [documentation](https://foxxmd.github.io/multi-scrobbler/docs/configuration/)
- [X] I have [searched through existing issues](https://github.com/FoxxMD/multi-scrobbler/issues?q=sort%3Aupdated-desc) and [discussions.](https://github.com/FoxxMD/multi-scrobbler/discussions)

### Describe the Bug

The app should scrobble the track artist and not the album artist.

I checked the documentation and see the [Scrobble Modifications section](https://foxxmd.github.io/multi-scrobbler/docs/configuration/transforms/#remove-various-artists-albums-in-all-new-plays) but I'm not sure if this can be used to replace the album artist with track artist.

### Platform

Docker

### Versions

- multi-scrobbler: latest on docker (0.8.8)
- plex: plexinc/pms-docker:latest

### Logs

```shell
[2024-12-16 08:33:54.431 -0700] ERROR  : [App] [Scrobblers] [Lastfm - captainnapalm83] Could not scrobble Various Artists - When You Wish Upon a Star @ 2024-12-16T08:29:30-07:00 (S) from Source 'Source - Plex - Megaplex++' due to error
Error: Could not scrobble Various Artists - When You Wish Upon a Star @ 2024-12-16T08:29:30-07:00 (S) from Source 'Source - Plex - Megaplex++' due to error
    at LastfmScrobbler.processDeadLetterScrobble (CWD/src/backend/scrobblers/AbstractScrobbleClient.ts:727:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at LastfmScrobbler.processDeadLetterQueue (CWD/src/backend/scrobblers/AbstractScrobbleClient.ts:694:43)
    at PromisePoolExecutor.handler (CWD/src/backend/tasks/heartbeatClients.ts:29:25)
    at async PromisePoolExecutor.waitForActiveTaskToFinish (CWD/node_modules/@supercharge/promise-pool/dist/promise-pool-executor.js:375:9)
    at async PromisePoolExecutor.waitForProcessingSlot (CWD/node_modules/@supercharge/promise-pool/dist/promise-pool-executor.js:368:13)
    at async PromisePoolExecutor.process (CWD/node_modules/@supercharge/promise-pool/dist/promise-pool-executor.js:354:13)
    at async PromisePoolExecutor.start (CWD/node_modules/@supercharge/promise-pool/dist/promise-pool-executor.js:273:16)
caused by: Error: LastFM ignored scrobble
    at LastfmScrobbler.doScrobble (CWD/src/backend/scrobblers/LastfmScrobbler.ts:155:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at LastfmScrobbler.processDeadLetterScrobble (CWD/src/backend/scrobblers/AbstractScrobbleClient.ts:720:39)
    at LastfmScrobbler.processDeadLetterQueue (CWD/src/backend/scrobblers/AbstractScrobbleClient.ts:694:43)
    at PromisePoolExecutor.handler (CWD/src/backend/tasks/heartbeatClients.ts:29:25)
    at async PromisePoolExecutor.waitForActiveTaskToFinish (CWD/node_modules/@supercharge/promise-pool/dist/promise-pool-executor.js:375:9)
    at async PromisePoolExecutor.waitForProcessingSlot (CWD/node_modules/@supercharge/promise-pool/dist/promise-pool-executor.js:368:13)
    at async PromisePoolExecutor.process (CWD/node_modules/@supercharge/promise-pool/dist/promise-pool-executor.js:354:13)
    at async PromisePoolExecutor.start (CWD/node_modules/@supercharge/promise-pool/dist/promise-pool-executor.js:273:16)
[2024-12-16 08:33:54.431 -0700] ERROR  : [App] [Scrobblers] [Lastfm - captainnapalm83] Scrobble Error (Backlog)
[2024-12-16 08:31:56.728 -0700] ERROR  : [App] [Scrobblers] [Lastfm - captainnapalm83] Scrobble Error (Backlog)
[2024-12-15 17:33:54.404 -0700] ERROR  : [App] [Scrobblers] [Lastfm - captainnapalm83] Could not scrobble Various Artists - The Evergreen @ 2024-12-15T17:12:53-07:00 (S) from Source 'Source - Plex - Megaplex++' due to error
Error: Could not scrobble Various Artists - The Evergreen @ 2024-12-15T17:12:53-07:00 (S) from Source 'Source - Plex - Megaplex++' due to error
    at LastfmScrobbler.processDeadLetterScrobble (CWD/src/backend/scrobblers/AbstractScrobbleClient.ts:727:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at LastfmScrobbler.processDeadLetterQueue (CWD/src/backend/scrobblers/AbstractScrobbleClient.ts:694:43)
    at PromisePoolExecutor.handler (CWD/src/backend/tasks/heartbeatClients.ts:29:25)
    at async PromisePoolExecutor.waitForActiveTaskToFinish (CWD/node_modules/@supercharge/promise-pool/dist/promise-pool-executor.js:375:9)
    at async PromisePoolExecutor.waitForProcessingSlot (CWD/node_modules/@supercharge/promise-pool/dist/promise-pool-executor.js:368:13)
    at async PromisePoolExecutor.process (CWD/node_modules/@supercharge/promise-pool/dist/promise-pool-executor.js:354:13)
    at async PromisePoolExecutor.start (CWD/node_modules/@supercharge/promise-pool/dist/promise-pool-executor.js:273:16)
caused by: Error: LastFM ignored scrobble
    at LastfmScrobbler.doScrobble (CWD/src/backend/scrobblers/LastfmScrobbler.ts:155:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at LastfmScrobbler.processDeadLetterScrobble (CWD/src/backend/scrobblers/AbstractScrobbleClient.ts:720:39)
    at LastfmScrobbler.processDeadLetterQueue (CWD/src/backend/scrobblers/AbstractScrobbleClient.ts:694:43)
    at PromisePoolExecutor.handler (CWD/src/backend/tasks/heartbeatClients.ts:29:25)
    at async PromisePoolExecutor.waitForActiveTaskToFinish (CWD/node_modules/@supercharge/promise-pool/dist/promise-pool-executor.js:375:9)
    at async PromisePoolExecutor.waitForProcessingSlot (CWD/node_modules/@supercharge/promise-pool/dist/promise-pool-executor.js:368:13)
    at async PromisePoolExecutor.process (CWD/node_modules/@supercharge/promise-pool/dist/promise-pool-executor.js:354:13)
    at async PromisePoolExecutor.start (CWD/node_modules/@supercharge/promise-pool/dist/promise-pool-executor.js:273:16)
```

**Comment by FoxxMD** [comment]
This should be fixed in the `foxxmd/multi-scrobbler:edge` docker image now. Please try it out and let me know if it resolves your issue.

**Comment by captainnapalm** [comment]
Yes, that has resolved the issue. Thanks for the quick turn-around!

**Comment by FoxxMD** [comment]
Fixed in [v0.9.0](https://github.com/FoxxMD/multi-scrobbler/releases/tag/0.9.0)
