### ISSUE TITLE
[Docker] Error using Jellyfin as source

### ISSUE THREAD

**Issue by bastianvv** [FoxxMD/multi-scrobbler#27]
**Environment:** Docker
**Version:** release-0.3.7
When setting up Jellyfin as a source, the container stops and logs show this error:

```
2021-07-01T21:01:20+00:00 warn   : [App] No scrobble clients were configured!
2021-07-01T21:01:20+00:00 error  : [App    ] Exited with uncaught error
2021-07-01T21:01:20+00:00 error  : [App    ] ReferenceError: user is not defined
    at new JellyfinSource (file://CWD/sources/JellyfinSource.js:14:36)
    at ScrobbleSources.addSource (file://CWD/sources/ScrobbleSources.js:259:46)
    at ScrobbleSources.buildSourcesFromConfig (file://CWD/sources/ScrobbleSources.js:220:32)
    at async file://CWD/index.js:150:9
```

My config file is this one:
```json
{
  "sourceDefaults": {
    "maxPollRetries": 0,
    "maxRequestRetries": 1,
    "retryMultiplier": 1.5
  },
  "clientDefaults": {
    "maxRequestRetries": 1,
    "retryMultiplier": 1.5
  },
  "sources": [
    {
      "type": "jellyfin",
      "name": "Jellyfin",
      "clients": [],
      "data": {       
        "users": ["jellyfinuser"],
        "servers": ["http://serverip:8096/"]
      }
    }
  ]
}
```

However, if I setup my config changing the "users" fields to "user", the container starts successfully and keeps running, and the logs now show:
```
2021-07-01T21:42:40+00:00 warn   : [App] No scrobble clients were configured!
2021-07-01T21:42:40+00:00 info   : [Jellyfin - Jellyfin] Initializing with the following filters => Users: N/A | Servers: http://serverip:8096/
2021-07-01T21:42:40+00:00 info   : [Sources            ] (Jellyfin) jellyfin source initialized
2021-07-01T21:42:40+00:00 info   : [App                ] Server started at http://serverip:9078

```
If i try and play some music from my Jellyfin server with the changes made to the config, the logs constantly show:
```
 [Jellyfin - Jellyfin] Will not scrobble event because server was not on allowed list: Jellyfin Server [{"artists":["<artistname>"],"track":"<trackname>"}]
```

**Comment by FoxxMD** [comment]
thanks for finding this bug ill take a look at this soon

**Comment by FoxxMD** [comment]
@bastianvv please try `latest` or `release-0.3.8` to see if that fixes your issue.

**Comment by FoxxMD** [comment]
P.S. in your jellyfin source if you want to specify the server you should use the server name, not the url
![2021-07-05_11-07](https://user-images.githubusercontent.com/4663766/124491403-3c78c700-dd81-11eb-9a55-e6e8ba21717c.png)

**Comment by bastianvv** [comment]
Ok, I updated my container to use release-0.3.8 image.
After that, I successfully configured the config file with the parameter "users" without any crashes. So yay!
Sadly, the multi-scrobbler log still shows the same message.
```
 [Jellyfin - Jellyfin] Will not scrobble event because server was not on allowed list: Jellyfin Server [{"artists":["<artistname>"],"track":"<trackname>"}]
```
I should add my setup is in a LAN, so although the Jellyfin server name is configured with the hostname, all access to it is done through the server LAN IP address + port.

This is my current multi-scrobbler config
```
{
  "sourceDefaults": {
    "maxPollRetries": 0,
    "maxRequestRetries": 1,
    "retryMultiplier": 1.5
  },
  "clientDefaults": {
    "maxRequestRetries": 1,
    "retryMultiplier": 1.5
  },
  "sources": [
    {
      "type": "jellyfin",
      "name": "serverhostname",
      "clients": [],
      "data": {
        "users": ["jellyfin_user"],
        "servers": ["http://serveripaddress:8096"]
      }
    }
  ],
  "clients": [
    {
     "type": "maloja",
     "name": "Maloja",
     "data": {
       "url": "http://serveripaddress:42010",
       "apiKey": "someapikey1234"
     }     
    },
    {
     "type": "lastfm",
     "name": "LastFM",
     "data": {
       "apiKey": "anotherapikey12345",
       "secret": "somesecret0987",
       "redirectUri": "http://serveripaddress:9078/lastfm/callback"
     }
    }
  ]
}
```
And this is my Webhook plugin config:
![webhook-config](https://user-images.githubusercontent.com/21223384/124522428-34d91280-ddc1-11eb-8b8e-23717d09778d.png)



Just in case, after playback starts in Jellyfin, this is the only relevant log for the Webhook Plugin. 
```
[2021-07-05 21:35:19.466 +00:00] [INF] [22] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0OyBydjo4OS4wKSBHZWNrby8yMDEwMDEwMSBGaXJlZm94Lzg5LjB8MTYyNDc1MTMxMzIzNg11-31280d8024f7469393f0238ab7255a8b-4e4bc889aa5fa6de2b68ef0257408ef1"
[2021-07-05 21:35:31.304 +00:00] [INF] [22] Emby.Server.Implementations.ScheduledTasks.TaskManager: "IntervalTrigger" fired for task: "Webhook Item Added Notifier"
[2021-07-05 21:35:31.304 +00:00] [INF] [22] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task "ItemAddedScheduledTask"
[2021-07-05 21:35:31.304 +00:00] [INF] [22] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Webhook Item Added Notifier"
[2021-07-05 21:35:31.304 +00:00] [INF] [22] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2021-07-05 21:35:31.308 +00:00] [INF] [22] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[2021-07-05 21:35:39.467 +00:00] [INF] [22] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : 
```

**Comment by FoxxMD** [comment]
I believe you are misunderstanding the usage of `servers` in the sources configuration.

Jellyfin initiates sending data to the multi-scrobbler instance, rather than multi-scrobbler initiating the request to Jellyfin. The server name is included in the payload Jellyfin sends. So it doesn't matter where or how your Jellyfin server is hosted mutli-scrobbler will always be able to parse the server name from the data Jellyfin sends. 

The `servers` property is not used for connecting to Jellyfin, it's used for filtering out which Jellyfin server should be used as the source (if there are multiple Jellyfin servers all pointed at the same multi-scrobbler instance).

So you still need to put the name of the sever in the `servers` property.

**Comment by bastianvv** [comment]
Thank you so much for the explanation. Indeed I completely misunderstood how it worked.
As recommended, I removed the "servers" property from my config and it worked immediately.
Tried again with the server name for testing sake, but I couldn't make it work.

Again, thanks for your help, and thanks for this awesome software.

**Comment by FoxxMD** [comment]
> Tried again with the server name for testing sake, but I couldn't make it work.

hmm then that might be a bug! I'll get around to testing that soonish but if you want to open an issue for that feel free.

Glad you're enjoy the software :)

**Comment by nothing2obvi** [comment]
I was having trouble using Jellyfin as a source, then I found this thread. Needed to remove the "servers" line from my config file as well; now it works!
