### ISSUE TITLE
Maloja config / comms errors? 

### ISSUE THREAD

**Issue by mannp** [FoxxMD/multi-scrobbler#38]
Not sure what I am doing wrong, as I am getting some strange errors from my maloja config;

```
[
  {
    "name": "maloja",          
    "data": {
      "url": "http://192.168.10.41:42010", 
      "apiKey": "734589764859678459678945678967457676475897648",
      "clientDefaults": {
        "maxRequestRetries": 2,      
        "retryMultiplier": 1.5
      }       
    }
  }
]
```

> Currently installed Maloja version: 2.14.5

Can you see anything that I am doing wrong? As I don't see why I am getting communication succeeded then failed?

Thanks.

```
2021-12-31T17:01:02+00:00 warn : [Scrobblers ] (maloja) maloja client auth OK
2021-12-31T17:01:02+00:00 info : [Client Maloja - maloja] Auth test passed!
2021-12-31T17:01:02+00:00 error : [Scrobblers ] (maloja) maloja client failed to initialize. Client needs to be successfully initialized before scrobbling.
2021-12-31T17:01:02+00:00 error : [Client Maloja - maloja] Error: Invalid argument not valid semver ('' received)
at validateAndParse (CWD/node_modules/compare-versions/index.js:38:13) at Array.forEach () at compareVersions (CWD/node_modules/compare-versions/index.js:66:14) at MalojaScrobbler.testConnection (file://CWD/clients/MalojaScrobbler.js:124:20) at processTicksAndRejections (internal/process/task_queues.js:95:5) at async MalojaScrobbler.initialize (file://CWD/clients/MalojaScrobbler.js:174:28) at async ScrobbleClients.addClient (file://CWD/clients/ScrobbleClients.js:230:17) at async ScrobbleClients.buildClientsFromConfig (file://CWD/clients/ScrobbleClients.js:195:17) at async file://CWD/index.js:134:9 2021-12-31T17:01:02+00:00 error : [Client Maloja - maloja] Communication test failed
2021-12-31T17:01:02+00:00 info : [Client Maloja - maloja] Maloja Server Version:
2021-12-31T17:01:02+00:00 info : [Client Maloja - maloja] Communication test succeeded.
```

I have also tried with the 'type' of maloja, but it gave me the same error.

**Comment by krateng** [comment]
Sorry, that's my fault - changed something with the API. I'll fix it asap.

**Comment by krateng** [comment]
2.14.6 should now work again, I hope.

**Comment by mannp** [comment]
Thanks for the quick response and fix 🙂

I did try 2.14.4 and that also failed the same, fyi.

Will give your update a try, thanks.

**Comment by FoxxMD** [comment]
Thanks @krateng !
