### ISSUE TITLE
cannot connect to maloja using >=0.3.10

### ISSUE THREAD

**Issue by cpuks** [FoxxMD/multi-scrobbler#39]
When I upgrade to latest which is 0.3.10 I cannot authenticate maloja - nothing changed according to changelog on both sides, I'm using latest tag for maloja and multi-scrobbler but 0.3.10 gives error and can't connect to maloja - using 0.3.9 solves issue.

**Comment by FoxxMD** [comment]
Can you provide any logs? Are you sure you have pulled the `latest` image for maloja? There was an [issue with a recent version of maloja that broke the way it reported its version.](https://github.com/FoxxMD/multi-scrobbler/issues/38)

**Comment by cpuks** [comment]
OK so:
`/usr/src/app # maloja info

#####
Maloja v2.14.6
https://github.com/krateng/maloja
#####

Configuration Directory: /config
Data Directory:          /config
Log Directory:           /config/logs
Network:                 IPv4, Port 42010
Timezone:                UTC+0`

`Fri, 07 Jan 2022 18:34:16 GMT express-session deprecated undefined resave option; provide resave option at file:/home/node/app/index.js:49:9
Fri, 07 Jan 2022 18:34:16 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at file:/home/node/app/index.js:49:9
2022-01-07T19:34:16+01:00 info : [Client Maloja - Maloja] Communication test succeeded.
2022-01-07T19:34:16+01:00 info : [Client Maloja - Maloja] Maloja Server Version: 2.14.6

2022-01-07T19:34:16+01:00 info : [Scrobblers ] (Maloja) maloja client initialized
2022-01-07T19:34:16+01:00 info : [Client Maloja - Maloja] Auth test passed!
2022-01-07T19:34:16+01:00 warn : [Scrobblers ] (Maloja) maloja client auth OK
2022-01-07T19:34:16+01:00 info : [Scrobblers ] (last.fm) lastfm client initialized
2022-01-07T19:34:17+01:00 info : [API - Lastfm - last.fm] Client authorized for user cpu
2022-01-07T19:34:17+01:00 warn : [Scrobblers ] (last.fm) lastfm client auth OK
2022-01-07T19:34:17+01:00 info : [Sources ] (sosnica) spotify source initialized
2022-01-07T19:34:17+01:00 info : [Sources ] (sosnica) spotify source auth OK
2022-01-07T19:34:19+01:00 info : [Source - Spotify - sosnica] Polling started
2022-01-07T19:34:19+01:00 info : [App ] Server started at http://localhost:9078`

When I click maloja reauth:
`Specified client does not have auth implemented (maloja)`

**Comment by FoxxMD** [comment]
Your logs look ok...can you try this and post your logs:

* Set `LOG_LEVEL` to `debug`
  * Running using node: `LOG_LEVEL=debug node index.js`
  * Docker: `run ... -e LOG_LEVEL=debug foxxmd/multi-scrobbler`
* Play a song on spotify and wait for it to be picked up my multi-scrobbler
* Post all logs here
