### ISSUE TITLE
Error on startup on Unraid

### ISSUE THREAD

**Issue by abb0r** [FoxxMD/multi-scrobbler#5]
I set the variables in the docker template for Plex and Maloja, but when starting the docker I get this error in the log:

```
2020-11-21T09:46:12+01:00 [App] info: No config file or could not be read (normal if using ENV vars only)
2020-11-21T09:46:12+01:00 [App] warn: Current spotify access token was not parsable or file does not exist (this could be normal)
2020-11-21T09:46:12+01:00 [App] warn: No spotify config file or could not be read (normal if using ENV vars only)
(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'accessToken' of undefined
at SpotifySource.buildSpotifyApi (file:///home/node/app/sources/SpotifySource.js:82:13)
at async file:///home/node/app/index.js:115:9
(Use `node --trace-warnings ...` to show where the warning was created)

(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by FoxxMD** [comment]
This should be fixed now. Update your container and let me know if its woring.

**Comment by abb0r** [comment]
Yes, the docker is working now, but it doesn't pick up any track from the Plex (and Tautulli) webhook.

**Comment by FoxxMD** [comment]
@abb0r can you try updating your container to use `foxxmd/multi-scrobbler:develop` and let me know if that fixes the issue? If nothing else it will provide more detailed error logging to help me debug your issue.

**Comment by crosbyh** [comment]
One data point, I was experiencing these same error messages using Tautulli, and updating to the develop branch resolved the issue.

**Comment by abb0r** [comment]
Plex webhook also works. Thanks for the fast fix!
