### ISSUE TITLE
Errors Scrobbling to Maloja

### ISSUE THREAD

**Issue by austincnunn** [FoxxMD/multi-scrobbler#57]
I am unable to scrobble to Maloja. I am playing from Spotify and scrobbling to Maloja. I get errors like this each time, and I can't seem to track down the issue: 

```
2022-12-01T14:34:27-05:00 error : [Scrobblers ] TypeError: Cannot read property 'album' of undefined
at MalojaScrobbler.scrobble (file://CWD/clients/MalojaScrobbler.js:526:32) at processTicksAndRejections (internal/process/task_queues.js:95:5) at async ScrobbleClients.scrobble (file://CWD/clients/ScrobbleClients.js:314:25) at async SpotifySource.doPolling (file://CWD/sources/AbstractSource.js:168:38) at async SpotifySource.startPolling (file://CWD/sources/AbstractSource.js:78:17) at async SpotifySource.poll (file://CWD/sources/SpotifySource.js:252:9) 2022-12-01T14:34:27-05:00 error : [Scrobblers ] Encountered error while in scrobble loop for unnamed
2022-12-01T14:34:27-05:00 error : [Client Maloja - unnamed ] Scrobble Error (Backlog) [{"payload":{"album":"The Essential Mary Chapin Carpenter","artists":["Mary Chapin Carpenter"],"key":"jYFmc7ZhSWsnNC4gUqtEuRNIxEJk2RrHcPbxfN5QgDsO5384mNWCv5TGYgFz5uKA","length":201.893,"time":1669922982,"title":"Down at the Twist and Shout"},"playInfo":"Mary Chapin Carpenter - Down at the Twist and Shout @ 2022-12-01T14:29:42-05:00"}]
```

I am running this on Unraid 6.11, fwiw.

**Comment by FoxxMD** [comment]
What version of maloja are you running? You can see this when first starting multi-scrobbler in the logs like this:

```
2022-12-06T10:32:38-05:00 info : [Client Maloja - default] Maloja Server Version: 3.1.4
```

**Comment by FoxxMD** [comment]
Hi, if you still have an issue with this I can re-open the issue once you've provided more information.

**Comment by toonvank** [comment]
Hey i encountered the same issue

2023-04-17T23:02:42+00:00 error : [Scrobblers] [Maloja - myMaloja] Encountered error while in scrobble loop
ErrorWithCause: at ScrobbleClients.scrobble (CWD/src/clients/ScrobbleClients.js:376:45) at runMicrotasks () at processTicksAndRejections (node:internal/process/task_queues:96:5) at async EventEmitter. (CWD/src/clients/ScrobbleClients.js:391:13) caused by: TypeError: Cannot read properties of undefined (reading 'album') at MalojaScrobbler.scrobble (CWD/src/clients/MalojaScrobbler.js:238:40) at runMicrotasks () at processTicksAndRejections (node:internal/process/task_queues:96:5) at async ScrobbleClients.scrobble (CWD/src/clients/ScrobbleClients.js:361:29) at async EventEmitter. (CWD/src/clients/ScrobbleClients.js:391:13)

**Comment by toonvank** [comment]
Running latest Maloja 3.1.5

**Comment by FoxxMD** [comment]
@toonvank can you tell me what track what being scrobbled at the time? From what source?

**Comment by toonvank** [comment]
The source is spotify. I'll check out that develop branch

**Comment by toonvank** [comment]
Also when i try to (re)authenticate with Maloja i get "Specified client does not have auth implemented (maloja)"

**Comment by FoxxMD** [comment]
> tried to switch to develop branch

It does not look like you are running MS with the updates I added...your stack trace is the same as the first one but should have been different with the updates I made. Additionally should have had [another log statement](https://github.com/FoxxMD/multi-scrobbler/blob/develop/src/clients/MalojaScrobbler.ts#L475) with the raw response recorded.

Are you running multi-scrobbler from the repo using node? Please make sure you are building the project after checking out the branch. Also please use the `debug` log level for more information:

* Check out `develop` branch
* Build: from the project directory run `npm run build`
* Run: from the project directory run `LOG_LEVEL=debug node src/index.js`

If you are using docker please make sure you are pulling the latest `develop` image.
