### ISSUE TITLE
Scrobbling from Jellyfin via Webhook Plugin not working

### ISSUE THREAD

**Issue by Karsten-Yan** [FoxxMD/multi-scrobbler#58]
At first i want to say: Thank you for your work on multiscrobbler, its working very well for me using spotify as a source and maloja as a client.

I have some problems getting scrobbling from jellyfin to work.

As far as i can tell i have configured everything correctly.

Config json for multiscrobbler looks like this:

    {
          "type": "jellyfin",
          "name": "jellyfin_karsten",
          "clients": [],
          "data": {
            "users": ["mrmori"],
            "servers": ["karsten-B450-AORUS-PRO"]
          }

For the generic webhook i checked the boxes necessary and webhook url is `http://192.168.178.81:9078/jellyfin`

When i play a song i get the following error in the jellyfin logs:

    [2022-12-28 09:25:07.615 +00:00] [WRN] [32] Jellyfin.Plugin.Webhook.Destinations.Generic.GenericClient: Notification failed with "POST" request to http://192.168.178.81:9078/jellyfin: "{\"ServerId\":\"db8f7e68bbd94fcc8976021c8bab496c\",\"ServerName\":\"karsten-B450-AORUS-PRO\",\"ServerVersion\":\"10.8.8\",\"ServerUrl\":\"http://192.168.178.47:8096\",\"NotificationType\":\"PlaybackProgress\",\"Timestamp\":\"2022-12-28T09:25:07.6021148+00:00\",\"UtcTimestamp\":\"2022-12-28T09:25:07.6021156Z\",\"Name\":\"The Escape\",\"Overview\":\"\",\"Tagline\":\"\",\"ItemId\":\"1be79aa1d0ed256d5c29202d6d4fbe5f\",\"ItemType\":\"Audio\",\"RunTimeTicks\":1090266624,\"RunTime\":\"00:01:49\",\"Year\":2018,\"Album\":\"Ni no Kuni II : Revenant Kingdom\",\"Artist\":\"Joe Hisaishi\",\"Audio_0_Title\":\"FLAC - Stereo\",\"Audio_0_Type\":\"Audio\",\"Audio_0_Language\":null,\"Audio_0_Codec\":\"flac\",\"Audio_0_Channels\":2,\"Audio_0_Bitrate\":660544,\"Audio_0_SampleRate\":44100,\"Audio_0_Default\":false,\"PlaybackPositionTicks\":10075660,\"PlaybackPosition\":\"00:00:01\",\"MediaSourceId\":\"1be79aa1d0ed256d5c29202d6d4fbe5f\",\"IsPaused\":false,\"IsAutomated\":true,\"DeviceId\":\"TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEwNC4wLjAuMCBTYWZhcmkvNTM3LjM2fDE2NjA4MTY5NzM0MjI1\",\"DeviceName\":\"Chrome\",\"ClientName\":\"Jellyfin Web\",\"NotificationUsername\":\"mrmori\",\"UserId\":\"d2e36d21fdca4beeb115ce6570afb754\"}"
    [2022-12-28 09:25:07.615 +00:00] [WRN] [32] Jellyfin.Plugin.Webhook.Destinations.Generic.GenericClient: Notification failed with response status code InternalServerError: "<!DOCTYPE html>
    <html lang=\"en\">
    <head>
    <meta charset=\"utf-8\">
    <title>Error</title>
    </head>
    <body>
    <pre>ReferenceError: hint is not defined<br> &nbsp; &nbsp;at JellyfinSource.isValidEvent (file:///home/node/app/sources/JellyfinSource.js:100:92)<br> &nbsp; &nbsp;at JellyfinSource.handle (file:///home/node/app/sources/JellyfinSource.js:142:19)<br> &nbsp; &nbsp;at file:///home/node/app/index.js:309:30<br> &nbsp; &nbsp;at wrappedMiddleware (/home/node/app/node_modules/@awaitjs/express/index.js:116:13)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/node/app/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/home/node/app/node_modules/express/lib/router/route.js:137:13)<br> &nbsp; &nbsp;at /home/node/app/node_modules/@awaitjs/express/index.js:131:8<br> &nbsp; &nbsp;at /home/node/app/node_modules/body-parser/lib/read.js:130:5<br> &nbsp; &nbsp;at invokeCallback (/home/node/app/node_modules/raw-body/index.js:224:16)<br> &nbsp; &nbsp;at done (/home/node/app/node_modules/raw-body/index.js:213:7)</pre>
    </body>
    </html>
    "
    [2022-12-28 09:25:07.615 +00:00] [ERR] [32] Jellyfin.Plugin.Webhook.WebhookSender: Unable to send notification
    System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
     ---> System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
       at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
       at System.Text.Json.Utf8JsonReader.Read()
       at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
       --- End of inner exception stack trace ---
       at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
       at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
       at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
       at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
       at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
       at Jellyfin.Plugin.Webhook.Destinations.GenericForm.GenericFormClient.SendAsync(GenericFormOption option, Dictionary`2 data)
       at Jellyfin.Plugin.Webhook.WebhookSender.SendNotification[T](IWebhookClient`1 webhookClient, T option, Dictionary`2 itemData, Type itemType)

Jellyfin Server version: 10.8.8
Maloja Version: 3.1.4
Multiscrobbler Version: 0.3.11

I am not sure how to interpret the error message, do you have any insights on this?

Thank you in advance!

**Comment by powellc** [comment]
Yeah, the fix is available in this PR: https://github.com/FoxxMD/multi-scrobbler/pull/56

You can pull that person's fork for now, as there haven't been a lot of other changes to this codebase in a while. Love the work! Just need to get a few PRs merged :)

**Comment by Karsten-Yan** [comment]
Thank you for the quick response, it works very nicely!

I should have looked at the pull requests before i opened the issue, but still very happy it is solved for now :)

**Comment by FoxxMD** [comment]
Sorry for the delay. I've merged the PR into develop (so available in the `develop` docker image). Will get it into master soon..

**Comment by powellc** [comment]
Brilliant! Thanks a million, @FoxxMD   Now I get to update my ansible script to not hot patch on deploy 🥳

**Comment by Karsten-Yan** [comment]
Nice, thank you for the quick reaction. Really enjoying your work!
