### ISSUE TITLE
Jellyfin ReferenceError

### ISSUE THREAD

**Issue by Vodes** [FoxxMD/multi-scrobbler#59]
I'm currently getting this error every time the webhook sends a request to the scrobbler.

```
scrobbler    | ReferenceError: hint is not defined
scrobbler    |     at JellyfinSource.isValidEvent (file:///home/node/app/sources/JellyfinSource.js:100:92)
scrobbler    |     at JellyfinSource.handle (file:///home/node/app/sources/JellyfinSource.js:142:19)
scrobbler    |     at file:///home/node/app/index.js:309:30
scrobbler    |     at wrappedMiddleware (/home/node/app/node_modules/@awaitjs/express/index.js:116:13)
scrobbler    |     at Layer.handle [as handle_request] (/home/node/app/node_modules/express/lib/router/layer.js:95:5)
scrobbler    |     at next (/home/node/app/node_modules/express/lib/router/route.js:137:13)
scrobbler    |     at /home/node/app/node_modules/@awaitjs/express/index.js:131:8
scrobbler    |     at /home/node/app/node_modules/body-parser/lib/read.js:130:5
scrobbler    |     at invokeCallback (/home/node/app/node_modules/raw-body/index.js:224:16)
scrobbler    |     at done (/home/node/app/node_modules/raw-body/index.js:213:7)
```

I'm running everything in Docker. Jellyfin Version 10.8.7 and whatever the currrently latest webhook plugin is.

Both the source and client are on *Awaiting Data* and lastfm is fully authenticated.

My config is currently looking like this

```json
{
   "sourceDefaults":{
      "maxPollRetries":0,
      "maxRequestRetries":1,
      "retryMultiplier":1.5
   },
   "clientDefaults":{
      "maxRequestRetries":1,
      "retryMultiplier":1.5
   },
   "sources":[
      {
         "type":"jellyfin",
         "name":"JF-Alex",
         "clients":[
            "lastfm-alex"
         ],
         "data":{
            "users":[
               "Alex"
            ]
         }
      }
   ],
   "clients":[
      {
         "type":"lastfm",
         "name":"lastfm-alex",
         "data":{
            "apiKey":"...",
            "secret":"...",
            "redirectUri":"..."
         }
      }
   ]
}
```

**Comment by FoxxMD** [comment]
I believe this should be fixed in the `develop` image/branch https://github.com/FoxxMD/multi-scrobbler/issues/58

**Comment by Vodes** [comment]
Okay yup the develop build seems to be working. Thanks.
