### ISSUE TITLE
Jellyfin Webhook post error

### ISSUE THREAD

**Issue by AngelPone** [FoxxMD/multi-scrobbler#61]
The post request from jellyfin webhook failed with response status code InternalServerError. The error message is 

```
TypeError: Cannot read property 'split' of undefined
    at Function.formatPlayObj (file:///home/node/app/sources/JellyfinSource.js:60:39)
    at file:///home/node/app/index.js:306:44
    at wrappedMiddleware (/home/node/app/node_modules/@awaitjs/express/index.js:116:13)
    at Layer.handle [as handle_request] (/home/node/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/node/app/node_modules/express/lib/router/route.js:137:13)
    at /home/node/app/node_modules/@awaitjs/express/index.js:131:8
    at wrappedMiddleware (/home/node/app/node_modules/@awaitjs/express/index.js:117:32)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
I guess it is because jellyfin posted a null Runtime, but I checked the post data, it was not the case.

```
[2023-01-14 20:27:31.965 +00:00] [WRN] [33] Jellyfin.Plugin.Webhook.Destinations.Generic.GenericClient: Notification failed with "POST" request to http://localhost:5879/jellyfin: "

{
    "ServerId": "c2957a8cee7841a1bf651916c38adeb5",
    "ServerName": "14535f67514f",
    "ServerVersion": "10.8.4",
    "ServerUrl": "",
    "NotificationType": "PlaybackProgress",
    "Timestamp": "2023-01-14T20:27:31.9570112+00:00",
    "UtcTimestamp": "2023-01-14T20:27:31.9570129Z",
    "Name": "\u795E\u6811",
    "Overview": "",
    "Tagline": "",
    "ItemId": "691a205da91791e42865dfdfda0d4600",
    "ItemType": "Audio",
    "RunTimeTicks": 3188640000,
    "RunTime": "00:05:18",
    "Year": 2020,
    "Album": "\u65B0\u4E16\u754CNEW WORLD",
    "Artist": "\u534E\u6668\u5B87",
    "Provider_musicbrainzalbumartist": "f3dcdc3c-3714-4ffb-b44a-a18632c4c630",
    "Provider_musicbrainzartist": "f3dcdc3c-3714-4ffb-b44a-a18632c4c630",
    "Provider_musicbrainzalbum": "3043d071-c8bc-412f-a483-d11169ec60e9",
    "Provider_musicbrainzreleasegroup": "52f83f60-fc39-45dd-8e82-f9b868888c98",
    "Provider_musicbrainztrack": "5e5f2e89-53c5-4b20-9053-03099e7b332a",
    "Audio_0_Title": "MP3 - Stereo",
    "Audio_0_Type": "Audio",
    "Audio_0_Language": null,
    "Audio_0_Codec": "mp3",
    "Audio_0_Channels": 2,
    "Audio_0_Bitrate": 320000,
    "Audio_0_SampleRate": 48000,
    "Audio_0_Default": false,
    "PlaybackPositionTicks": 962868310,
    "PlaybackPosition": "00:01:36",
    "MediaSourceId": "691a205da91791e42865dfdfda0d4600",
    "IsPaused": false,
    "IsAutomated": true,
    "DeviceId": "TW96aWxsYS81LjAgKE1hY2ludG9zaDsgSW50ZWwgTWFjIE9TIFggMTBfMTVfNykgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEwNS4wLjAuMCBTYWZhcmkvNTM3LjM2fDE2NjQxODM3MTI4OTU1",
    "DeviceName": "Chrome",
    "ClientName": "Jellyfin Web",
    "NotificationUsername": "myname",
    "UserId": "myid"
}
```

**Comment by AngelPone** [comment]
I tried to post the same data use curl, it returned OK. So strange. But  no  message appeared in the log file of multi-scrobbler.

**Comment by AngelPone** [comment]
Close it because I worked out.

**Comment by FoxxMD** [comment]
What was the issue?

**Comment by arminius-smh** [comment]
@FoxxMD I don't know if this is related, but Jellyfin doesn't work as a json config file for me too, IF I include my user- and servername, like in the jellyfin example file - I can't really have any mistakes there my username is just "armin"  and my server is named "jellyfin"
If I leave the data field empty everything works fine.

The odd thing is that the environment variables don't seem to have any effect for me, no matter what I type in JELLYFIN_USER and JELLYFIN_SERVER, the Jellyfin Source always get initialized with no filters, as the log reports (which overall would "work" for my use-case, maybe the same thing occured to @AngelPone ?)
