### ISSUE TITLE
Stuck on Spotify Auth

### ISSUE THREAD

**Issue by jansendotsh** [FoxxMD/multi-scrobbler#63]
I'm sure this is probably a "user error" however I've set up Maloja and Multi-Scrobbler on a remote server via Docker. As of now, I can scrobble directly to Maloja, Plex scrobbling works via Multi-Scrobbler, however I'm stuck on Spotify auth. 

When I click "Reauth and restart polling", it brings up a window that has me login to Spotify, returns an "OK" and then I can close. Multi-Scrobbler seems to have some troubles though with the following error consistently logged:

```
 2023-01-31T17:04:04+00:00 error : [Source - Spotify - unnamed ] Cannot start polling because user interaction is required for authentication
```

The setup is via docker-compose, shared below:

```docker
version: '3.3'
services:
  multiscrobbler:
    image: foxxmd/multi-scrobbler:latest
    container_name: multiscrobbler
    ports:
      - 9078:9078
    environment:
      - SPOTIFY_CLIENT_ID=redacted
      - SPOTIFY_CLIENT_SECRET=redacted
      - SPOTIFY_REDIRECT_URI=http://multiscrobbler.jansen.sh:9078/callback
      - MALOJA_URL=https://maloja.jansen.sh
      - MALOJA_API_KEY=redacted
      - PLEX_USER=frailtyy
    volumes:
      - multiscrob:/home/node/app/config
    labels:
      - diun.enable=true

volumes:
  multiscrob:
```

I'm _guessing_ there might be an issue writing the obtained token to a file but it's just a Docker volume, SELinux disabled and everything:

```
[root@despair docker-multiscrobbler]#  docker exec -it multiscrobbler ls -larth /home/node/app/config
total 36K
-rw-r--r--    1 node     node         726 Apr 28  2022 tautulli.json.example
-rw-r--r--    1 node     node         500 Apr 28  2022 subsonic.json.example
-rw-r--r--    1 node     node        1.2K Apr 28  2022 spotify.json.example
-rw-r--r--    1 node     node         726 Apr 28  2022 plex.json.example
-rw-r--r--    1 node     node         377 Apr 28  2022 maloja.json.example
-rw-r--r--    1 node     node        1.4K Apr 28  2022 lastfm.json.example
-rw-r--r--    1 node     node         610 Apr 28  2022 jellyfin.json.example
-rw-r--r--    1 node     node        1.1K Apr 28  2022 deezer.json.example
-rw-r--r--    1 node     node        1.7K Apr 28  2022 config.json.example
drwxr-sr-x    1 node     node         254 Apr 28  2022 ..
drwxr-xr-x    1 node     node         352 Jan 31 07:18 .
```

Any thoughts on troubleshooting this one? There's likely an easy fix here staring me right in the face.

**Comment by jansendotsh** [comment]
If it helps, I'm seeing the following logs in the container:

```
2023-01-31T17:31:11+00:00 info   : [App                        ] Redirecting to spotify authorization url
2023-01-31T17:42:59+00:00 info   : [Spotify                    ] Received auth code callback from Spotify [{"label":"Spotify"}]
TypeError: Cannot read property 'handleAuthCodeCallback' of undefined
    at file:///home/node/app/index.js:479:50
    at wrappedMiddleware (/home/node/app/node_modules/@awaitjs/express/index.js:116:13)
    at Layer.handle [as handle_request] (/home/node/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/node/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/node/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/node/app/node_modules/express/lib/router/layer.js:95:5)
    at /home/node/app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/node/app/node_modules/express/lib/router/index.js:335:12)
    at next (/home/node/app/node_modules/express/lib/router/index.js:275:10)
    at SessionStrategy.strategy.pass (/home/node/app/node_modules/passport/lib/middleware/authenticate.js:337:9)
2023-01-31T19:55:04+00:00 info   : [Spotify                    ] Received auth code callback from Spotify [{"label":"Spotify"}]
TypeError: Cannot read property 'handleAuthCodeCallback' of undefined
    at file:///home/node/app/index.js:479:50
    at wrappedMiddleware (/home/node/app/node_modules/@awaitjs/express/index.js:116:13)
    at Layer.handle [as handle_request] (/home/node/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/node/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/node/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/node/app/node_modules/express/lib/router/layer.js:95:5)
    at /home/node/app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/node/app/node_modules/express/lib/router/index.js:335:12)
    at next (/home/node/app/node_modules/express/lib/router/index.js:275:10)
    at SessionStrategy.strategy.pass (/home/node/app/node_modules/passport/lib/middleware/authenticate.js:337:9)
2023-01-31T19:55:09+00:00 info   : [Spotify                    ] Received auth code callback from Spotify [{"label":"Spotify"}]
TypeError: Cannot read property 'handleAuthCodeCallback' of undefined
    at file:///home/node/app/index.js:479:50
    at wrappedMiddleware (/home/node/app/node_modules/@awaitjs/express/index.js:116:13)
    at Layer.handle [as handle_request] (/home/node/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/node/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/node/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/node/app/node_modules/express/lib/router/layer.js:95:5)
    at /home/node/app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/node/app/node_modules/express/lib/router/index.js:335:12)
    at next (/home/node/app/node_modules/express/lib/router/index.js:275:10)
    at SessionStrategy.strategy.pass (/home/node/app/node_modules/passport/lib/middleware/authenticate.js:337:9)
```

**Comment by FoxxMD** [comment]
Thanks those logs helped. Can you try the `foxxmd/multi-scrobbler:develop` image and see if that fixes things for you?
