### ISSUE TITLE
BUG: config.json could not be parsed

### ISSUE THREAD

**Issue by rumpff** [FoxxMD/multi-scrobbler#64]
I can't launch multi-scrobbler with json config. I tried both one config file and multiple config files for lastfm and tautulli. 

i get this error when i run "node index.js"

```pwsh
warn   : [App] App config file exists but could not be parsed!
error  : [App] Exited with uncaught error
error  : [App] Error: config.json could not be parsed
    at ScrobbleClients.buildClientsFromConfig (file:///C:/Users/Administrator/Documents/multi-scrobbler/clients/ScrobbleClients.js:41:19)
    at async file:///C:/Users/Administrator/Documents/multi-scrobbler/index.js:134:9
```
 
my config.json file looks like this:

```json
{
  "sourceDefaults": {
    "maxPollRetries": 0,          
    "maxRequestRetries": 1,       
    "retryMultiplier": 1.5      
  },
  "clientDefaults": {
    "maxRequestRetries": 1,       
    "retryMultiplier": 1.5       
  },
  "sources": [
    {
      "type": "tautulli",         
      "name": "myTautulli",                                       
      "clients": ["myLFM"],
      "data": {
        "user": ["myName"] 
      }
    }
  ],
  "clients": [
    {
      "type": "lastfm",
      "name": "myLFM",
      "data": {
        "apiKey": "xxxxxxxxxxx",
        "secret": "xxxxxxxxxxx"
      }
    }
  ]
}
```

with 2 seperate json files i still get an error for the client but the server does boot up
im running node v16.13.0 on Windows

**Comment by FoxxMD** [comment]
Your json is syntactically correct and valid for MS:

```
XXXX/.nvm/versions/node/v16.13.0/bin/node XXX/multi-scrobbler/index.js

2023-02-03T11:14:26-05:00 info   : [Scrobblers] (myLFM) lastfm client initialized
2023-02-03T11:14:26-05:00 info   : [API - Lastfm - myLFM] No session key found. User interaction for authentication required.
2023-02-03T11:14:26-05:00 warn   : [Scrobblers          ] (myLFM) lastfm client auth failed.
2023-02-03T11:14:26-05:00 info   : [Source - Tautulli - myTautulli] Initializing with the following filters => Users: myname | Libraries: N/A | Servers: N/A
2023-02-03T11:14:26-05:00 info   : [Sources                       ] (myTautulli) tautulli source initialized
2023-02-03T11:14:26-05:00 info   : [App                           ] Server started at http://localhost:9078
```

My guess is the file has [line-ending issues](https://www.cs.toronto.edu/~krueger/csc209h/tut/line-endings.html) due to being created on windows. Here's how to convert a file to **Unix** line endings with [vs code](https://medium.com/bootdotdev/how-to-get-consistent-line-breaks-in-vs-code-lf-vs-crlf-e1583bf0f0b6) or [notepad++](https://stackoverflow.com/a/57115055).

**Comment by rumpff** [comment]
changing the line endings didn't solve the issue

what did was removing the original comments that i left in from the example config
it seems that the comments were causing the issue
